In [473]:
import pandas as pd

In [474]:
recipes_df = pd.read_json('panelinha_dessert_recipes.json')
recipes_df.shape

(535, 11)

In [475]:
recipes_df.tail()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
530,Torta prática de maçã verde,doces,https://panelinha.com.br/receita/torta-pratica...,https://i.panelinha.com.br/i1/bk-7150-blog-ayu...,Maravilhosa! Essa é a melhor definição para es...,"[[2 xícaras (chá) de farinha de trigo, 100 g d...",Panelinha,Até 2h,8 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
531,Cuca de Uva,doces,https://panelinha.com.br/receita/cuca-de-uva,https://i.panelinha.com.br/i1/bk-4931-cuca-uva...,"Cuca não é bem um bolo, nem bem uma torta. É t...",[[2 xícaras (chá) de uva preta debulhada (vitó...,Panelinha,Até 2h,12 pedaços,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
532,Musse de chocolate a jato com manga e maracujá,doces,https://panelinha.com.br/receita/musse-chocola...,https://i.panelinha.com.br/i1/bk-1359-blog-ayu...,Esta é a musse de chocolate com o preparo mais...,"[[1 manga, 1 maracujá, 150 g de chocolate amar...",Panelinha,Pá-Pum,Até 4 porções,"[[Descasque e corte a manga em cubos de 1,5 cm...",{}
533,Creme batido,doces,https://panelinha.com.br/receita/creme-batido,https://i.panelinha.com.br/i1/bk-4819-receita-...,"Uma colherada de creme de leite no café, na to...",[[1 xícara (chá) de creme de leite fresco gela...,Panelinha,Pá-Pum,1 ¾ xícara (chá),[[Coloque o creme de leite gelado numa tigela ...,{}
534,Muffin de banana na Air Fryer Oven da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-banana...,https://i.panelinha.com.br/i1/bk-6546-16885056...,"As bananas cortadas em pedacinhos, a massa per...","[[2 bananas-prata maduras, 2 ovos, ½ xícara (c...",Panelinha,Pá-Pum,9 unidades,[[Unte com manteiga 9 forminhas médias para em...,{}

In [476]:
recipes_df.isnull().sum()

name           0
category       0
link           0
img            0
description    0
ingredients    0
author         0
time           0
serves         0
steps          0
nutrients      0
dtype: int64

In [477]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         535 non-null    object
 1   category     535 non-null    object
 2   link         535 non-null    object
 3   img          535 non-null    object
 4   description  535 non-null    object
 5   ingredients  535 non-null    object
 6   author       535 non-null    object
 7   time         535 non-null    object
 8   serves       535 non-null    object
 9   steps        535 non-null    object
 10  nutrients    535 non-null    object
dtypes: object(11)
memory usage: 46.1+ KB

In [478]:
recipes_df.describe()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
count,535,535,535,535,535,535,535,535,535,535,535
unique,372,1,372,372,371,371,14,4,102,372,1
top,Pera picante com sorvete de canela,doces,https://panelinha.com.br/receita/pera-picante-...,https://i.panelinha.com.br/i1/bk-7841-pera-pic...,Eles já são um ícone do Natal. A mistura de es...,"[[¾ de xícara (chá) de creme de leite fresco, ...",Panelinha,Pá-Pum,Até 6 porções,[[Deixe o sorvete fora do freezer por 20 minut...,{}
freq,3,535,3,3,4,3,510,168,99,3,535

In [479]:
recipes_df['name'].unique()

array(['Muffin de mirtilo', 'Choux com chocolate e raspas de laranja',
       'Cobertura de bolo (ganache)', 'Bolinho de chocolate com ganache',
       'Doce de abóbora em pasta na panela de pressão elétrica',
       'Bolo flor de crepe com doce de leite', 'Crepe Suzette',
       'Pudim de chocolate', 'Ganache perfumada', 'Calda de mel',
       'Minipanetone com gotas de chocolate na Air Fryer da Rita Lobo',
       'Panetone com gotas de chocolate',
       'Torta de iogurte na Air Fryer da Rita Lobo',
       'Nhá Beth (merengue com chocolate)',
       'Pastel de goiabada com queijo na Air Fryer da Rita Lobo',
       'Pastel de banana com chocolate na Air Fryer da Rita Lobo',
       'Suflê de chocolate na Air Fryer da Rita Lobo',
       'Biscoito de castanha-do-pará', 'Éclair de Natal',
       'Cookie de banana com aveia e amendoim',
       'Barrinha de tâmara com cacau',
       'Bolo de caneca de maçã e amendoim (de micro-ondas)',
       'Bolo de caneca de banana com doce de leite',
       'Sequilho de polvilho', 'Chocolate quente com canela',
       'Pão doce de canela na Air Fryer da Rita Lobo',
       'Bolo de chocolate com gengibre',
       'Bolo de mandioca com coco na Air Fryer da Rita Lobo',
       'Geleia morna de frutas vermelhas com cardamomo', 'Amendoim doce',
       'Pipoca doce com chocolate', 'Pipoca doce com especiarias',
       'Pudim de Milho',
       'Bolinho de tapioca com coco e gengibre na Air Fryer da Rita Lobo',
       'Bolo de Fubá na Air Fryer da Rita Lobo',
       'Bolo de amêndoas com maçã na Air Fryer da Rita Lobo',
       'Pavlova com baba de moça', 'Cookie-brownie',
       'Bombom de sorvete de iogurte com framboesa',
       'Bombom de sorvete de café', 'Bombom de sorvete de doce de leite',
       'Bombom de sorvete', 'Rabanada na Air Fryer da Rita Lobo',
       'Minipanetone na Air Fryer da Rita Lobo',
       'Canjica na panela de pressão elétrica',
       'Brigadeirão na panela de pressão elétrica',
       'Cookie de abóbora e chocolate',
       'Crumble de banana com chocolate branco',
       'Trufinhas de chocolate com laranja e canela',
       'Crocante de gergelim', 'Pudim de tahine com crocante de gergelim',
       'Merengue de mel',
       'Banana assada na Air Fryer da Rita Lobo com merengue de mel',
       'Tarte tatin prática', 'Musse de chocolate de liquidificador',
       'Torta brookie', 'Bombocado na Air Fryer da Rita Lobo',
       'Biscoito de amêndoas (amaretti)',
       'Blondie com banana e castanha-de-caju',
       'Bolo invertido de abacaxi',
       'Bolinho de banana-da-terra com tapioca na Air Fryer da Rita Lobo',
       'Sorvete de iogurte com goiabada', 'Rocambole de laranja',
       'Brigadeiro de milho-verde', 'Pipoca doce',
       'Torrada de mel na Air Fryer da Rita Lobo', 'Torrada de mel',
       'Brownie na Air Fryer da Rita Lobo',
       'Pudim de panetone na panela de pressão elétrica',
       'Sagu de coco na panela de pressão elétrica',
       'Banana assada na Air Fryer da Rita Lobo',
       'Creme de confeiteiro com raspas de laranja e cardamomo',
       'Alecrim açucarado na Air Fryer da Rita Lobo',
       'Pavetone com pêssego',
       'Manjar de coco com calda de manga e maracujá',
       'Calda de manga e maracujá', 'Biscoito amanteigado de Natal',
       'Figo em calda na panela de pressão elétrica',
       'Broa recheada com creme de café',
       'Broa caxambu com doce de leite', 'Broa caxambu',
       'Broa brûlée (reaproveitamento)', 'Creme de confeiteiro',
       'Brownie de chocolate com café', 'Sorvete de cookie com leite',
       'Bolo de iogurte com limão',
       'Pudim de leite na panela de pressão elétrica',
       'Minipudim de leite',
       'Rabanada de pão de fôrma integral (reaproveitamento)',
       'Calda de chocolate com cachaça', 'Creme de abacate com sorvete',
       'Rabanada', 'Rosca de reis', 'Semifredo de doce de leite com café',
       'Pé de moleque com semente de coentro', 'Boston cheesecake',
       'Shortbread (biscoitos amanteigados)',
       'Manga flambada com cachaça', 'Merengue com água de grão-de-bico',
       'Bolo de banana', 'Ovo de Páscoa meio amargo com frutas secas',
       'Fondue de chocolate de micro-ondas', 'Sorbet de manga',
       'Sorvete de banana', 'Bolo delícia de limão',
       'Biscoito de chocolate duplo',
       'Pudim de rabanada com peras carameladas',
       'Brownie de chocolate branco com matcha',
       'Bolinho de chocolate com castanha-de-caju e mel', 'Crème brûlée',
       'Creme inglês', 'Bombom de damasco e amêndoas', 'Crema catalana',
       'Farofa doce de castanha-de-caju com raspas de laranja',
       'Uvas gratinadas', 'Bolo fudge de chocolate',
       'Creme batido perfumado', 'Bolo de sorvete com calda de caramelo',
       'Manjar branco', 'Bolo gelado de abacaxi', 'Bolo de laranja',
       'Torta de ricota com pêssegos macerados', 'Pudim de inhame',
       'Torta de pêssego com amêndoas',
       'Bolinho quente de doce de leite na Air Fryer da Rita Lobo',
       'Rabanada de arroz-doce', 'Panetone recheado com sorvete',
       'Sequilho', 'Bolo de sorvete com coco e baba de moça',
       'Biscoito de gengibre natalino', 'Palmier',
       'Baked Alaska de Panetone (reaproveitamento)',
       'Trufas de chocolate',
       'Pudim de mandioca com cumaru (reaproveitamento)',
       'Musse de chocolate branco',
       'Gelatina de vinho branco com especiarias',
       'Bolo de limão com glacê',
       'Bolo de sorvete com calda de frutas vermelhas',
       'Doce de leite caseiro', 'Pavlova na Air Fryer da Rita Lobo',
       'Macarons', 'Brownie da Maguy',
       'Doce de cenoura indiano (Gajar ka halwa)',
       'Frutas cozidas ao curry', 'Papo de anjo', 'Cuca de banana',
       'Cookie com chocolate e castanha-de-caju',
       'Bolo de milho de caneca', 'Cobertura de cream cheese para bolos',
       'Pavlova com frutas', 'Pão de especiarias ao chocolate diet',
       'Cocada branca', 'Canjica com raspas de laranja e mel', 'Malabie',
       'Brigadeiro de micro-ondas',
       'Suflê de goiabada com creme de mascarpone', 'Compota de caju',
       'Peras assadas no micro-ondas', 'Ambrosia rápida de leite em pó',
       'Tuiles de baunilha', 'Bolo de chocolate com amendoim',
       'Cocada da Paloma', 'Sorvete de chá verde', 'Cocada mole',
       'Biscoito de chocolate com castanha-do-pará', 'Glacê festivo',
       'Muffin de banana na Air Fryer Oven da Rita Lobo', 'Creme batido',
       'Musse de chocolate a jato com manga e maracujá', 'Cuca de Uva',
       'Torta prática de maçã verde',
       'Casca de ovos para decorar e rechear',
       'Geleia de maçã com ameixa', 'Biscoito de vinho',
       'Ganache (cobertura ou recheio de bolo)',
       'Petit gâteau de chocolate', 'Sacolé de iogurte com coco',
       'Pudim de doce de leite', 'Lemon curd',
       'Tarte tatin individual de abacaxi',
       'Sopa de manga e gengibre com frutas e sorvete de coco',
       'Kulfi de cenoura (sorvete indiano)',
       'Bagunça de morango com calda de cachaça', 'Gratin des fruits',
       'Pudim de leite com furinhos', 'Rocambole suflê de chocolate',
       'Sorvete de banana com cookies de aveia',
       'Pera picante com sorvete de canela', 'Bolo de mel e maçã',
       'Rabanadas com baunilha', 'Quindão',
       'Espiral de banana caramelizada',
       'Bolo perfeito de banana caramelada', 'Brigadeiro de panela',
       'Mont blanc - purê de castanhas',
       'Abacaxi flambado com sorvete de coco',
       'Pêssego ao vinho com mascarpone', 'Chremslach', 'Banana foster',
       'Torta de nozes', 'Baba de moça',
       'Bolo de chocolate com coco na caneca (de micro-ondas)',
       'Suflê de banana e laranja',
       'Tostex de banana com creme de avelã e chocolate',
       'Beijinho de colher', 'Pudim de pão integral com creme de avelã',
       'Pudim de leite sem furinhos',
       'Crème brûlée de gengibre ao perfume de laranja e baunilha',
       'Philo strudel', 'Bolo de mandioca cremoso com calda de coco',
       'Pé de moleque com laranja',
       'Bolo cremoso de chocolate com damasco e nozes',
       'Crepe com compota de morangos', 'Bombom de goiaba',
       'Muffin de amêndoas e passas', 'Sagu de café',
       'Crocante perfumado de castanha-de-caju',
       'Bolinho quente de doce de leite para dois', 'Torta de banana',
       'Sorvete de baunilha', 'Suflê de chocolate com calda de chocolate',
       'Crumble de uva com maçã', 'Tigelinhas de suspiro com maracujá',
       'Sopa de capim-santo com papaia',
       'Morango flambado com sorvete de creme', 'Waffle (favo holandês)',
       'Manjar de coco', 'Compota de chuchu com frutas e vinho',
       'Bolo de maçã com farofa de coco',
       'Batata-doce em calda com merengue', 'Cookie com sorvete e café',
       'Sagu de coco com manga grelhada', 'Pamonha com coco',
       'Crumble de pera com frutas vermelhas',
       'Rosca doce de cenoura com ameixa',
       'Morango com creme batido e água de rosas',
       'Geleia de morango com maracujá', 'Cuscuz de tapioca com coco',
       'Zuppa Inglese (reaproveitamento)', 'Creme de abacate congelado',
       'Curau', 'Bolo de aniversário dos meus filhos',
       'Rocambole (pão de ló com fécula de batata)',
       'Affogato (café com sorvete)',
       'Abacaxi grelhado com licor de laranja',
       'Bolo de crepe com geleia de morango e maracujá',
       'Brownie cremoso de castanha-do-pará',
       'Rocambole com geleia de framboesa', 'Biscoito 1 2 3',
       'Brigadeiro de tahine (de micro-ondas)',
       'Rabanadas com licor de laranja',
       'Creme de papaia congelado com licor de cassis',
       'Bolo inglês clássico (Pound cake)', 'Bolo inglês com frutas',
       'Tartine de maçã com mel e canela',
       'Iogurte com berries e suspiros no pote',
       'Panqueca americana de banana-da-terra', 'Tarte tatin',
       'Musse de chocolate com café', 'Massa para torta doce',
       'Gemada com vinho do Porto', 'Zabaione com folhas de chocolate',
       'Crumble de peras ao vinho',
       'Babka com brigadeiro de canela e laranja', 'Torta quente de maçã',
       'Submarino de chocolate',
       'Arroz-doce com especiarias (cúrcuma, cardamomo e canela)',
       'Brigadeiro tradicional',
       'Brigadeiro de micro-ondas com chocolate amargo',
       'Crocante de pêssego', 'Crumble de abóbora', 'Pastel de banana',
       'Maçã do amor', 'Sonho', 'Biscoito de marzipã',
       'Gomos de laranja macerados', 'Leite condensado caseiro',
       'Ovo de Páscoa meio amargo', 'Manteiga de maçã (apple butter)',
       'Panacota de café', 'Crepe de morango',
       'Polenta doce com peras ao vinho', 'Rabanada brûlée em palitos',
       'Raspadinha de mamão com gengibre', 'Cocada de forno',
       'Biscoitos amanteigados',
       'Arroz-doce com macerado de ameixa e vinho do Porto',
       'Bolo de Paçoca', 'Arroz-doce perfumado com cardamomo',
       'Biscoito de gengibre', 'Brigadeiro de abóbora e amêndoas',
       'Pavlova tropical', 'Arroz-doce cremoso', 'Brigadeiro de colher',
       'Arroz-doce na panela de pressão elétrica',
       'Arroz-doce com calda de caramelo e flor de sal',
       'Arroz-doce tradicional', 'Bolo cremoso de chocolate',
       'Creme brûlée com lavanda', 'Ricota com minipera grelhada',
       'Bolo de cenoura com especiarias (carrot cake)',
       'Tarte tatin de frigideira',
       'Bolinho de chuva de abóbora com chocolate',
       'Concord - bolo suspiro',
       'Bolo de cenoura com merengue e pistache',
       'Cuscuz de tapioca de colher', 'Bolo de amêndoa com coco e uva',
       'Geleia de jabuticaba', 'Suflê de goiabada com requeijão',
       'Musse de dois chocolates',
       'Pudim de leite na Air Fryer da Rita Lobo', 'Blondie com amêndoas',
       'Bolo musse de chocolate', 'Bolo de curau cremoso',
       'Biscoitone (panetone coberto de chocolate)',
       'Cocadinha francesa (reaproveitamento)', 'Biscoito de laranja',
       'Pão de mel', 'Torta de chocolate com damasco',
       'Bolo floresta negra', 'Granola na Air Fryer da Rita Lobo',
       'Musse de morango', 'Brownie rústico com cardamomo',
       'Ovinhos de chocolate', 'Merengue italiano (marshmallow)',
       'Rocambole de doce de leite', 'Musse de chocolate',
       'Creme de chantilly', 'Gemada perfeita', 'Torta de figo',
       'Cheesecake com calda de damasco', 'Bolo de pamonha',
       'Bolo de chocolate sem farinha', 'Farofa de aveia',
       'Pera cozida no micro-ondas com mel e canela',
       'Panqueca americana de chocolate (pancakes)', 'Bombocado',
       'Doce de leite de corte',
       'Salada de frutas primaveril com cachaça',
       'Banana dourada com merengue',
       'Pudim de tapioca com calda de coco queimado', 'Banana flambada',
       'Suflê de chocolate', 'Biscoitão de frigideira',
       'Musse de amora e cassis', 'Bolo em camadas de chocolate',
       'Merengue suíço', 'Panetone com frutas e sorvete',
       'Ovo de Páscoa ao leite pintado', 'Salada de frutas ao vinho',
       'Ovinhos pintados', 'Batata-doce ao leite de coco',
       'Torta de banana com nozes e especiarias',
       'Geleia de pêssego com chuchu e vinho',
       'Banana caramelada com suspiro',
       'Musse que vira suflê (de véspera)',
       'Sorvete de chocolate com amêndoas', 'Pain perdu de challah',
       'Bolo-rei', 'Manga grelhada com sorvete de banana',
       'Rabanada de pão de fôrma com raspas de laranja',
       'Bolo de fubá com limão e castanha-de-caju',
       'Bolo de banana com uva-passa', 'Amendoim açucarado',
       'Doce de mamão verde', 'Rolinhos de canela',
       'Pera com especiarias e calda de chocolate',
       'Barra de aveia e maçã', 'Musse de iogurte com calda de abacaxi',
       'Musse de limão-siciliano', 'Geleia de morango',
       'Torta de castanha-de-caju e damasco'], dtype=object)

In [480]:
len(recipes_df['name'].unique())

372

In [481]:
recipes_df.name.value_counts()

name
Pera picante com sorvete de canela                               3
Sorvete de banana com cookies de aveia                           3
Bolo de mel e maçã                                               3
Rabanadas com baunilha                                           3
Quindão                                                          3
                                                                ..
Minipanetone com gotas de chocolate na Air Fryer da Rita Lobo    1
Calda de mel                                                     1
Ganache perfumada                                                1
Pudim de chocolate                                               1
Crepe Suzette                                                    1
Name: count, Length: 372, dtype: int64

In [482]:
# recipes_df.loc[recipes_df['name'] == 'Bolo perfeito de banana caramelada']
recipes_df[recipes_df['name'] == 'Bolo perfeito de banana caramelada']

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
241,Bolo perfeito de banana caramelada,doces,https://panelinha.com.br/receita/bolo-perfeito...,https://i.panelinha.com.br/i1/bk-4571-ep-13-ba...,Um bolo que perfuma a casa toda antes mesmo de...,"[[1 xícara (chá) de açúcar, ½ xícara (chá) de ...",Panelinha,Até 2h,Mais de 6 porções,"[[Descasque e divida cada banana em 3 fatias, ...",{}
463,Bolo perfeito de banana caramelada,doces,https://panelinha.com.br/receita/bolo-perfeito...,https://i.panelinha.com.br/i1/bk-4571-ep-13-ba...,Um bolo que perfuma a casa toda antes mesmo de...,"[[1 xícara (chá) de açúcar, ½ xícara (chá) de ...",Panelinha,Até 2h,Mais de 6 porções,"[[Descasque e divida cada banana em 3 fatias, ...",{}

In [483]:
recipes_df.groupby('name').groups

{'Abacaxi flambado com sorvete de coco': [248, 483], 'Abacaxi grelhado com licor de laranja': [297], 'Affogato (café com sorvete)': [296], 'Alecrim açucarado na Air Fryer da Rita Lobo': [72], 'Ambrosia rápida de leite em pó': [192, 221, 492], 'Amendoim açucarado': [499], 'Amendoim doce': [29], 'Arroz-doce com calda de caramelo e flor de sal': [348], 'Arroz-doce com especiarias (cúrcuma, cardamomo e canela)': [319], 'Arroz-doce com macerado de ameixa e vinho do Porto': [339], 'Arroz-doce cremoso': [345], 'Arroz-doce na panela de pressão elétrica': [347], 'Arroz-doce perfumado com cardamomo': [341], 'Arroz-doce tradicional': [349], 'Baba de moça': [253], 'Babka com brigadeiro de canela e laranja': [316], 'Bagunça de morango com calda de cachaça': [224, 235, 457], 'Baked Alaska de Panetone (reaproveitamento)': [142, 154, 376], 'Banana assada na Air Fryer da Rita Lobo': [70], 'Banana assada na Air Fryer da Rita Lobo com merengue de mel': [52], 'Banana caramelada com suspiro': [476], 'Banana dourada com merengue': [449], 'Banana flambada': [451], 'Banana foster': [251, 480], 'Barra de aveia e maçã': [515], 'Barrinha de tâmara com cacau': [20], 'Batata-doce ao leite de coco': [473], 'Batata-doce em calda com merengue': [282], 'Beijinho de colher': [257], 'Biscoito 1 2 3': [301], 'Biscoito amanteigado de Natal': [76], 'Biscoito de amêndoas (amaretti)': [57], 'Biscoito de castanha-do-pará': [17], 'Biscoito de chocolate com castanha-do-pará': [200, 512], 'Biscoito de chocolate duplo': [106, 129, 405], 'Biscoito de gengibre': [342], 'Biscoito de gengibre natalino': [140, 153, 375], 'Biscoito de laranja': [382], 'Biscoito de marzipã': [327], 'Biscoito de vinho': [209, 527], 'Biscoitone (panetone coberto de chocolate)': [380], 'Biscoitos amanteigados': [338], 'Biscoitão de frigideira': [453], 'Blondie com amêndoas': [365], 'Blondie com banana e castanha-de-caju': [58], 'Bolinho de banana-da-terra com tapioca na Air Fryer da Rita Lobo': [60], 'Bolinho de chocolate com castanha-de-caju e mel': [112, 167, 434], 'Bolinho de chocolate com ganache': [3], 'Bolinho de chuva de abóbora com chocolate': [355], 'Bolinho de tapioca com coco e gengibre na Air Fryer da Rita Lobo': [33], 'Bolinho quente de doce de leite na Air Fryer da Rita Lobo': [135, 146, 368], 'Bolinho quente de doce de leite para dois': [270], 'Bolo cremoso de chocolate': [350], 'Bolo cremoso de chocolate com damasco e nozes': [264], 'Bolo de Fubá na Air Fryer da Rita Lobo': [34], 'Bolo de Paçoca': [340], 'Bolo de amêndoa com coco e uva': [360], 'Bolo de amêndoas com maçã na Air Fryer da Rita Lobo': [35], 'Bolo de aniversário dos meus filhos': [294], 'Bolo de banana': [100, 412], 'Bolo de banana com uva-passa': [490], 'Bolo de caneca de banana com doce de leite': [22], 'Bolo de caneca de maçã e amendoim (de micro-ondas)': [21], 'Bolo de cenoura com especiarias (carrot cake)': [353], 'Bolo de cenoura com merengue e pistache': [358], 'Bolo de chocolate com amendoim': [194, 219, 494], 'Bolo de chocolate com coco na caneca (de micro-ondas)': [254], 'Bolo de chocolate com gengibre': [26], 'Bolo de chocolate sem farinha': [423], 'Bolo de crepe com geleia de morango e maracujá': [298], 'Bolo de curau cremoso': [379], 'Bolo de fubá com limão e castanha-de-caju': [489], 'Bolo de iogurte com limão': [85], 'Bolo de laranja': [124, 428], 'Bolo de limão com glacê': [157, 394], 'Bolo de mandioca com coco na Air Fryer da Rita Lobo': [27], 'Bolo de mandioca cremoso com calda de coco': [262], 'Bolo de maçã com farofa de coco': [281], 'Bolo de mel e maçã': [230, 245, 467], 'Bolo de milho de caneca': [179, 185, 506], 'Bolo de pamonha': [411], 'Bolo de sorvete com calda de caramelo': [121, 169, 436], 'Bolo de sorvete com calda de frutas vermelhas': [158, 393], 'Bolo de sorvete com coco e baba de moça': [139, 150, 372], 'Bolo delícia de limão': [105, 130, 404], 'Bolo em camadas de chocolate': [455], 'Bolo flor de crepe com doce de leite': [5], 'Bolo floresta negra': [385], 'Bolo fudge de chocolate': [119, 171, 438], 'Bolo gelado de abacaxi': [123, 426], 'Bolo inglês clássico (Pound cake)': [305], 'Bolo inglês com frutas': [306], 'Bolo invertido de abacaxi': [59], 'Bolo musse de chocolate': [378], 'Bolo perfeito de banana caramelada': [241, 463], 'Bolo-rei': [486], 'Bombocado': [446], 'Bombocado na Air Fryer da Rita Lobo': [56], 'Bombom de damasco e amêndoas': [115, 357], 'Bombom de goiaba': [266], ...}

In [484]:
# recipes_df.groupby('name')['name'].size().sort_values(ascending=False)
recipes_df.groupby('name')['name'].count().sort_values(ascending=False)

name
Bagunça de morango com calda de cachaça                     3
Baked Alaska de Panetone (reaproveitamento)                 3
Sequilho                                                    3
Sorbet de manga                                             3
Sorvete de banana                                           3
                                                           ..
Arroz-doce perfumado com cardamomo                          1
Arroz-doce na panela de pressão elétrica                    1
Arroz-doce cremoso                                          1
Arroz-doce com macerado de ameixa e vinho do Porto          1
Arroz-doce com especiarias (cúrcuma, cardamomo e canela)    1
Name: name, Length: 372, dtype: int64

In [485]:
res = (recipes_df.groupby('name')['name'].count()>1).values
res

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False,  True, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True, False, False,
        True, False, False, False, False,  True,  True,  True, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True,  True, False, False, False, False,  True,
        True, False, False,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False, False, False, False,
       False, False,  True, False, False,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False,  True,  True, False, False, False,  True,  True,
        True, False, False, False, False, False, False, False,  True,
        True,  True, False, False, False,  True, False, False,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False,  True, False,  True, False,
        True, False, False, False, False, False,  True,  True, False,
        True, False, False,  True,  True,  True,  True, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False, False,  True, False,  True,  True, False,
       False, False, False])

In [486]:
recipes_df.duplicated(subset=['name', 'link'])

0      False
1      False
2      False
3      False
4      False
       ...
530     True
531     True
532     True
533     True
534     True
Length: 535, dtype: bool

In [487]:
recipes_df.duplicated(subset=['name', 'link']).sum()

np.int64(163)

In [488]:
recipes_df = recipes_df.drop_duplicates(subset=['name', 'link'], keep='first', ignore_index=True)
recipes_df.describe()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
count,372,372,372,372,372,372,372,372,372,372,372
unique,372,1,372,372,371,371,14,4,102,372,1
top,Torta de castanha-de-caju e damasco,doces,https://panelinha.com.br/receita/torta-de-cast...,https://i.panelinha.com.br/i1/bk-6158-design-s...,Eles já são um ícone do Natal. A mistura de es...,"[[1 lata de leite condensado (395 g), 2 ovos, ...",Panelinha,Pá-Pum,Até 6 porções,"[[Numa tigela pequena, quebre o ovo, adicione ...",{}
freq,1,372,1,1,2,2,357,114,70,1,372

In [489]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         372 non-null    object
 1   category     372 non-null    object
 2   link         372 non-null    object
 3   img          372 non-null    object
 4   description  372 non-null    object
 5   ingredients  372 non-null    object
 6   author       372 non-null    object
 7   time         372 non-null    object
 8   serves       372 non-null    object
 9   steps        372 non-null    object
 10  nutrients    372 non-null    object
dtypes: object(11)
memory usage: 32.1+ KB

In [490]:
recipes_df.head(7)

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
0,Muffin de mirtilo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-7970-blog-muf...,O sucesso deste muffin está no contraste de te...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Até 1h,9 unidades,"[[Numa tigela, misture os ingredientes com a p...",{}
1,Choux com chocolate e raspas de laranja,doces,https://panelinha.com.br/receita/choux-com-cho...,https://i.panelinha.com.br/i1/bk-2502-chouxcot...,"Com gotas de chocolate e raspas de laranja, a ...","[[50 g de manteiga em ponto pomada, ⅓ de xícar...",Panelinha,Até 2h,14 unidades,"[[Na tigela da batedeira, coloque todos os ing...",{}
2,Cobertura de bolo (ganache),doces,https://panelinha.com.br/receita/cobertura-de-...,https://i.panelinha.com.br/i1/bk-4162-blog-cob...,A receita perfeita de ganache existe: textura ...,"[[1¾ de xícara (chá) de creme de leite fresco,...",Panelinha,Até 1h,essa receita cobre 12 bolinhos individuais (ou...,"[[Caso não esteja usando chocolate em gotas, p...",{}
3,Bolinho de chocolate com ganache,doces,https://panelinha.com.br/receita/bolinho-de-ch...,https://i.panelinha.com.br/i1/bk-8769-blog-bol...,Chocolate e ganache formam uma dupla difícil d...,[[2¼ de xícaras (chá) de chocolate 55% cacau e...,Panelinha,Mais de 2h,12 minibolos,"[[Caso não esteja usando chocolate em gotas, p...",{}
4,Doce de abóbora em pasta na panela de pressão ...,doces,https://panelinha.com.br/receita/doce-de-abobo...,https://i.panelinha.com.br/i1/bk-1867-blog-doc...,O doce de abóbora em pasta fica com sabor bem ...,"[[1 kg de abóbora de pescoço descascada, 2 xíc...",Panelinha,Até 1h,8 porções,"[[Corte em pedaços médios, de cerca de 3 cm — ...",{}
5,Bolo flor de crepe com doce de leite,doces,https://panelinha.com.br/receita/bolo-flor-de-...,https://i.panelinha.com.br/i1/bk-1175-blog-bol...,Este bolo chama atenção na mesa: a montagem é ...,"[[3 ovos, 2¼ de xícaras (chá) de leite, 1½ xíc...",Panelinha,Até 2h,10 porções,"[[Numa tigela pequena, quebre um ovo de cada v...",{}
6,Crepe Suzette,doces,https://panelinha.com.br/receita/crepe-suzette,https://i.panelinha.com.br/i1/bk-5180-blog-cre...,"Clássico da confeitaria, o crepe Suzette combi...","[[¾ de xícara (chá) de leite, ½ xícara (chá) d...",Panelinha,Até 1h,5 crepes,[[Quebre o ovo numa tigela média e mexa com o ...,{}

In [491]:
ingredients = recipes_df[recipes_df.name == 'Choux com chocolate e raspas de laranja']['ingredients'].items()
for ingredient in ingredients:
    print(ingredient[1])

[['50 g de manteiga em ponto pomada', '⅓ de xícara (chá) de açúcar demerara', '½ xícara (chá) de farinha de trigo'], ['½ xícara (chá) de farinha de trigo peneirada', '½ xícara (chá) de chocolate 55% cacau em gotas (cerca de 90 g)', '¼ de xícara (chá) de leite', '¼ de xícara (chá) de água', '5 colheres (sopa) de manteiga (cerca de 60g)', '1 colher (chá) de açúcar', '¼ de colher (chá) de sal', '2 ovos', 'raspas de 1 laranja-baía']]

In [492]:
ingredients = []
for x in recipes_df[recipes_df.name == 'Choux com chocolate e raspas de laranja']['ingredients'].explode().array:
   ingredients.extend(x) 
ingredients_dict = {'name': 'Choux com chocolate e raspas de laranja', 'ingredients': ingredients}
ingredients_df = pd.DataFrame(ingredients_dict)
ingredients_df

,name,ingredients
0,Choux com chocolate e raspas de laranja,50 g de manteiga em ponto pomada
1,Choux com chocolate e raspas de laranja,⅓ de xícara (chá) de açúcar demerara
2,Choux com chocolate e raspas de laranja,½ xícara (chá) de farinha de trigo
3,Choux com chocolate e raspas de laranja,½ xícara (chá) de farinha de trigo peneirada
4,Choux com chocolate e raspas de laranja,½ xícara (chá) de chocolate 55% cacau em gotas...
5,Choux com chocolate e raspas de laranja,¼ de xícara (chá) de leite
6,Choux com chocolate e raspas de laranja,¼ de xícara (chá) de água
7,Choux com chocolate e raspas de laranja,5 colheres (sopa) de manteiga (cerca de 60g)
8,Choux com chocolate e raspas de laranja,1 colher (chá) de açúcar
9,Choux com chocolate e raspas de laranja,¼ de colher (chá) de sal
10,Choux com chocolate e raspas de laranja,2 ovos
11,Choux com chocolate e raspas de laranja,raspas de 1 laranja-baía

In [493]:
ingredients_df = recipes_df[['name', 'ingredients']].copy()
ingredients_df = ingredients_df.explode('ingredients').explode('ingredients')
ingredients_df

,name,ingredients
0,Muffin de mirtilo,1 colher (sopa) de manteiga gelada
0,Muffin de mirtilo,2 colheres (sopa) de açúcar
0,Muffin de mirtilo,2 colheres (sopa) de farinha de trigo
0,Muffin de mirtilo,¾ de xícara (chá) de mirtilo fresco (cerca de ...
0,Muffin de mirtilo,1 xícara (chá) de farinha de trigo
...,...,...
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar
371,Torta de castanha-de-caju e damasco,2 ovos
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...
371,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...
371,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho

In [494]:
import spacy
import pt_core_news_sm

nlp = spacy.load('pt_core_news_sm')

In [495]:
nlp.get_pipe('ner').labels

('LOC', 'MISC', 'ORG', 'PER')

In [496]:
print(spacy.explain('LOC'))
print(spacy.explain('MISC'))
print(spacy.explain('ORG'))
print(spacy.explain('PER'))

Non-GPE locations, mountain ranges, bodies of water
Miscellaneous entities, e.g. events, nationalities, products or works of art
Companies, agencies, institutions, etc.
Named person or family.

In [497]:
items = ingredients_df.head(20)['ingredients'].values
text = ' '.join(items)
print(text)
doc = nlp(text)
for ent in doc.ents:
    print(f'{ent.text} -> {ent.label_}')

1 colher (sopa) de manteiga gelada 2 colheres (sopa) de açúcar 2 colheres (sopa) de farinha de trigo ¾ de xícara (chá) de mirtilo fresco (cerca de 125g) 1 xícara (chá) de farinha de trigo ¾ de xícara (chá) de açúcar 1 colher (chá) de fermento em pó ⅓ de xícara (chá) de iogurte natural sem açúcar nem adoçante 50 g de manteiga 1 ovo raspas de 1 limão-siciliano 50 g de manteiga em ponto pomada ⅓ de xícara (chá) de açúcar demerara ½ xícara (chá) de farinha de trigo ½ xícara (chá) de farinha de trigo peneirada ½ xícara (chá) de chocolate 55% cacau em gotas (cerca de 90 g) ¼ de xícara (chá) de leite ¼ de xícara (chá) de água 5 colheres (sopa) de manteiga (cerca de 60g) 1 colher (chá) de açúcar
⅓ -> MISC
⅓ -> MISC
manteiga -> LOC

In [498]:
spacy.displacy.render(doc, style='ent', jupyter=True)

In [499]:
ingredients_df

,name,ingredients
0,Muffin de mirtilo,1 colher (sopa) de manteiga gelada
0,Muffin de mirtilo,2 colheres (sopa) de açúcar
0,Muffin de mirtilo,2 colheres (sopa) de farinha de trigo
0,Muffin de mirtilo,¾ de xícara (chá) de mirtilo fresco (cerca de ...
0,Muffin de mirtilo,1 xícara (chá) de farinha de trigo
...,...,...
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar
371,Torta de castanha-de-caju e damasco,2 ovos
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...
371,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...
371,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho

In [500]:
ingredients_df[ingredients_df['ingredients'].astype(str).str.contains(r'\bkg\b', case=False, na=False)]

,name,ingredients
4,Doce de abóbora em pasta na panela de pressão ...,1 kg de abóbora de pescoço descascada
100,Ovo de Páscoa meio amargo com frutas secas,1 kg de chocolate meio amargo
132,Trufas de chocolate,1 kg de chocolate meio amargo
177,Pudim de doce de leite,1 kg de açúcar
194,Mont blanc - purê de castanhas,1 kg de castanha portuguesa
270,Crumble de abóbora,1 kg de abóbora de pescoço descascada
278,Manteiga de maçã (apple butter),1 kg de maçã fuji (4 a 5 unidades)
307,Geleia de jabuticaba,1 kg de jabuticaba
348,Ovo de Páscoa ao leite pintado,1 kg de chocolate ao leite
351,Batata-doce ao leite de coco,1 kg de batata-doce
364,Doce de mamão verde,1 kg de mamão verde
364,Doce de mamão verde,"1,5 kg de açúcar"

In [501]:
import re
import pandas as pd

# Extract likely measurement units from ingredient strings
standard_measure_pattern = re.compile(r"\b(?:grama|gramas|kg|g|ml|l|oz|lbs|mg|cm|mm|m)\b", re.IGNORECASE)
household_unit_pattern = re.compile(r"\b(?:xícara|xícaras|colher|colheres|copo|copos|pitada|pitadas|pacote|pacotes|envelope|envelopes|unidade|unidades|lata|latas|pedaço|pedaços|fatia|fatias|tbsp|tsp|cup|cups|caixa|caixas)\b(?:\s*\((?:chá|sopa)\))?", re.IGNORECASE)

units = []
for value in ingredients_df['ingredients'].dropna():
    units.extend(standard_measure_pattern.findall(str(value)))

sorted_units = sorted({u.lower() for u in units})
print(f'{sorted_units}')
print(f'{len(sorted_units)} unique standard measurement units found in the ingredients.')
# units

['cm', 'g', 'kg', 'ml']
4 unique standard measurement units found in the ingredients.

In [502]:
import unicodedata

def convert_vulgar_fraction(text):
    text = list(text)
    fractions = [(i, unicodedata.normalize("NFKC", char)) for i, char in enumerate(text) if 'VULGAR FRACTION' in unicodedata.name(char)]
    if len(fractions) > 0:
        for pos, normalized_fraction in fractions:
            text[pos] = normalized_fraction
    return ''.join(text)

# '2 cenouras (cerca de 240g ou 1 ½ xícara (chá) descascada e ralada)'
# '174 ml de água quente (⅔ de xícara (chá) + 1 colher (sopa))'
# '⅔ de xícara (chá) de damasco seco cortado em cubos de 0,5 cm (cerca de 125 g)'
ing_a = '⅔ de xícara (chá) de damasco seco cortado em cubos de 0,5 cm (cerca de 125 g)'
ing_a = convert_vulgar_fraction(ing_a)

ing_b = '320 g de açúcar demerara (ou cristal) (1 ½ xícara (chá))'
ing_b = convert_vulgar_fraction(ing_b)

ing_c = 'raspas de 30 limões sicilianos'
ing_c = convert_vulgar_fraction(ing_c)

ing_d = 'caldo de ½ limão'
ing_d = convert_vulgar_fraction(ing_d)

ing_e = '3 claras de ovo'
ing_e = convert_vulgar_fraction(ing_e)

ing_f = '½ pacote de gelatina em pó incolor e sem sabor (6 g)'
ing_f = convert_vulgar_fraction(ing_f)

ing_g = '2 ¼ latas de milho-verde (cerca de 2 xícaras [chá] de grãos escorridos)'
ing_g = convert_vulgar_fraction(ing_g)

entities = {'entities': []}

standard_measures = 'grama|gramas|kg|g|ml|l|oz|lbs|mg'
household_measures = 'xícaras|xícara|colheres|colher|copos|copo|pitadas|pitada|pacotes|pacote|envelopes|envelope|unidades|unidade|latas|lata|pedaços|pedaço|fatias|fatia|tbsp|tsp|cups|cup|caixas|caixa'

quantity_regex = '(?P<quantity>(\d+\s+\d+\N{FRACTION SLASH}\d+|\d+\N{FRACTION SLASH}\d+|\d+(?!\s+\d+))(\.\d+|\,\d+)?)'

standard_measure_regex = fr'\b{quantity_regex}(?:\s*)(?P<mesure>{standard_measures})\b'
household_measure_regex = fr'{quantity_regex}(?:\s*\w*\s*)(?P<mesure>(?:{household_measures})((\s*\((chá|sopa)\))|(\s*\[(chá|sopa)\]))?)'
unit_regex = f'\s*{quantity_regex}\s+(?!(?:de\s+)?(?:{household_measures}|{standard_measures}|cm|mm|m)(?:\s+|\)))'

standard_measure_pattern = re.compile(
    fr'{standard_measure_regex}', 
    flags=re.IGNORECASE
)
household_measure_pattern = re.compile(
    fr'{household_measure_regex}',
    flags=re.IGNORECASE
)
unit_pattern = re.compile(
    fr'{unit_regex}', 
    re.IGNORECASE
)

entities = {'entities': []}

standard_matches = standard_measure_pattern.finditer(ing_a)
for match in standard_matches:
    entities['entities'].append((match.start('quantity'), match.end('mesure'), 'MEDIDA_PADRAO'))

household_matches = household_measure_pattern.finditer(ing_a)
for match in household_matches:
    entities['entities'].append((match.start('quantity'), match.end('mesure'), 'MEDIDA_CASEIRA'))

unit_matches = unit_pattern.finditer(ing_a)
for match in unit_matches:
    entities['entities'].append((match.start('quantity'), match.end('quantity'), 'UNIDADE'))

entities['entities'].sort(key=lambda x: x[0])
tupla = (ing_a, entities)
print(f"{tupla}")

('2⁄3 de xícara (chá) de damasco seco cortado em cubos de 0,5 cm (cerca de 125 g)', {'entities': [(0, 19, 'MEDIDA_CASEIRA'), (73, 78, 'MEDIDA_PADRAO')]})

In [503]:
ingredients_df['ingredients_fractional'] = ingredients_df['ingredients'].apply(lambda x: convert_vulgar_fraction(x))

standard_measures = 'grama|gramas|kg|g|ml|l|oz|lbs|mg'
household_measures = 'xícaras|xícara|colheres|colher|copos|copo|pitadas|pitada|pacotes|pacote|envelopes|envelope|unidades|unidade|latas|lata|pedaços|pedaço|fatias|fatia|tbsp|tsp|cups|cup|caixas|caixa'

quantity_regex = '(?P<quantity>(\d+\s+\d+\N{FRACTION SLASH}\d+|\d+\N{FRACTION SLASH}\d+|\d+(?!\s+\d+))(\.\d+|\,\d+)?)'

standard_measure_regex = fr'\b{quantity_regex}(?:\s*)(?P<mesure>{standard_measures})\b'
household_measure_regex = fr'{quantity_regex}(?:\s*\w*\s*)(?P<mesure>(?:{household_measures})((\s*\((chá|sopa)\))|(\s*\[(chá|sopa)\]))?)'
unit_regex = f'\s*{quantity_regex}\s+(?!(?:de\s+)?(?:{household_measures}|{standard_measures}|cm|mm|m)(?:\s+|\)))'

standard_measure_pattern = re.compile(
    fr'{standard_measure_regex}', 
    flags=re.IGNORECASE
)
household_measure_pattern = re.compile(
    fr'{household_measure_regex}',
    flags=re.IGNORECASE
)
unit_pattern = re.compile(
    fr'{unit_regex}', 
    re.IGNORECASE
)

def create_entities(text):
    entities = {'entities': []}

    standard_matches = standard_measure_pattern.finditer(text)
    for match in standard_matches:
        entities['entities'].append((match.start('quantity'), match.end('mesure'), 'MEDIDA_PADRAO'))

    household_matches = household_measure_pattern.finditer(text)
    for match in household_matches:
        entities['entities'].append((match.start('quantity'), match.end('mesure'), 'MEDIDA_CASEIRA'))

    unit_matches = unit_pattern.finditer(text)
    for match in unit_matches:
        entities['entities'].append((match.start('quantity'), match.end('quantity'), 'UNIDADE'))

    entities['entities'].sort(key=lambda x: x[0])
    return entities

ingredients_df['entities'] = ingredients_df['ingredients_fractional'].apply(create_entities)
ingredients_df

,name,ingredients,ingredients_fractional,entities
0,Muffin de mirtilo,1 colher (sopa) de manteiga gelada,1 colher (sopa) de manteiga gelada,"{'entities': [(0, 15, 'MEDIDA_CASEIRA')]}"
0,Muffin de mirtilo,2 colheres (sopa) de açúcar,2 colheres (sopa) de açúcar,"{'entities': [(0, 17, 'MEDIDA_CASEIRA')]}"
0,Muffin de mirtilo,2 colheres (sopa) de farinha de trigo,2 colheres (sopa) de farinha de trigo,"{'entities': [(0, 17, 'MEDIDA_CASEIRA')]}"
0,Muffin de mirtilo,¾ de xícara (chá) de mirtilo fresco (cerca de ...,3⁄4 de xícara (chá) de mirtilo fresco (cerca d...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (48, ..."
0,Muffin de mirtilo,1 xícara (chá) de farinha de trigo,1 xícara (chá) de farinha de trigo,"{'entities': [(0, 14, 'MEDIDA_CASEIRA')]}"
...,...,...,...,...
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar,1⁄2 xícara (chá) de açúcar,"{'entities': [(0, 16, 'MEDIDA_CASEIRA')]}"
371,Torta de castanha-de-caju e damasco,2 ovos,2 ovos,"{'entities': [(0, 1, 'UNIDADE')]}"
371,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...,1⁄2 xícara (chá) de castanha-de-caju torrada s...,"{'entities': [(0, 16, 'MEDIDA_CASEIRA'), (73, ..."
371,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...,2⁄3 de xícara (chá) de damasco seco cortado em...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (73, ..."
371,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho,1 colher (chá) de amido de milho,"{'entities': [(0, 14, 'MEDIDA_CASEIRA')]}"

In [504]:
ingredients_df[ingredients_df['entities'] == {'entities': []}]

,name,ingredients,ingredients_fractional,entities
3,Bolinho de chocolate com ganache,manteiga para untar a fôrma,manteiga para untar a fôrma,{'entities': []}
3,Bolinho de chocolate com ganache,cacau em pó para polvilhar,cacau em pó para polvilhar,{'entities': []}
5,Bolo flor de crepe com doce de leite,manteiga para untar a frigideira,manteiga para untar a frigideira,{'entities': []}
5,Bolo flor de crepe com doce de leite,açúcar de confeiteiro para polvilhar,açúcar de confeiteiro para polvilhar,{'entities': []}
5,Bolo flor de crepe com doce de leite,morangos cortados a gosto para servir,morangos cortados a gosto para servir,{'entities': []}
...,...,...,...,...
365,Rolinhos de canela,azeite para untar a tigela,azeite para untar a tigela,{'entities': []}
365,Rolinhos de canela,manteiga para untar a assadeira,manteiga para untar a assadeira,{'entities': []}
365,Rolinhos de canela,farinha de trigo para polvilhar a bancada,farinha de trigo para polvilhar a bancada,{'entities': []}
367,Barra de aveia e maçã,manteiga e farinha de trigo para untar e polvi...,manteiga e farinha de trigo para untar e polvi...,{'entities': []}
371,Torta de castanha-de-caju e damasco,farinha de trigo integral para polvilhar a ban...,farinha de trigo integral para polvilhar a ban...,{'entities': []}

In [505]:
# ingredients_df[ingredients_df['ingredients'].str.contains(r'\+')]
# ingredients_df[ingredients_df['ingredients'].str.contains('cm')]
# ingredients_df[ingredients_df['ingredients'].str.contains(r'\[')]
ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'\d+\s+\d+(?:\N{FRACTION SLASH}\d+)?')]
# 2 cenouras (cerca de 240g ou 1 1⁄2 xícara (chá) descascada e ralada)
# 2 latas de milho-verde (cerca de 2 1⁄4 xícaras [chá] de grãos escorridos)

,name,ingredients,ingredients_fractional,entities
32,Pudim de Milho,2 latas de milho-verde (cerca de 2 ¼ xícaras [...,2 latas de milho-verde (cerca de 2 1⁄4 xícaras...,"{'entities': [(0, 7, 'MEDIDA_CASEIRA'), (33, 5..."
90,Creme de abacate com sorvete,caldo de 1 ½ limão,caldo de 1 1⁄2 limão,"{'entities': [(9, 14, 'UNIDADE')]}"
220,Suflê de chocolate com calda de chocolate,⅓ de xícara (chá) + 1 ½ colher (sopa) de açúca...,1⁄3 de xícara (chá) + 1 1⁄2 colher (sopa) de a...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (22, ..."
248,Biscoito 1 2 3,300 g de farinha de trigo ou 2 ½ xícaras (chá),300 g de farinha de trigo ou 2 1⁄2 xícaras (chá),"{'entities': [(0, 5, 'MEDIDA_PADRAO'), (29, 48..."
276,Leite condensado caseiro,320 g de açúcar demerara (ou cristal) (1 ½ xíc...,320 g de açúcar demerara (ou cristal) (1 1⁄2 x...,"{'entities': [(0, 5, 'MEDIDA_PADRAO'), (39, 57..."
300,Bolo de cenoura com especiarias (carrot cake),2 cenouras (cerca de 240g ou 1 ½ xícara (chá) ...,2 cenouras (cerca de 240g ou 1 1⁄2 xícara (chá...,"{'entities': [(0, 1, 'UNIDADE'), (21, 25, 'MED..."

In [506]:
ingredients_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2920 entries, 0 to 371
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    2920 non-null   object
 1   ingredients             2920 non-null   object
 2   ingredients_fractional  2920 non-null   object
 3   entities                2920 non-null   object
dtypes: object(4)
memory usage: 114.1+ KB