In [79]:
import pandas as pd

In [80]:
recipes_df = pd.read_json('panelinha_dessert_recipes.json')
recipes_df.shape

(541, 11)

In [81]:
recipes_df.tail()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
536,Torta prática de maçã verde,doces,https://panelinha.com.br/receita/torta-pratica...,https://i.panelinha.com.br/i1/bk-7150-blog-ayu...,Maravilhosa! Essa é a melhor definição para es...,"[[2 xícaras (chá) de farinha de trigo, 100 g d...",Panelinha,Até 2h,8 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
537,Cuca de Uva,doces,https://panelinha.com.br/receita/cuca-de-uva,https://i.panelinha.com.br/i1/bk-4931-cuca-uva...,"Cuca não é bem um bolo, nem bem uma torta. É t...",[[2 xícaras (chá) de uva preta debulhada (vitó...,Panelinha,Até 2h,12 pedaços,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
538,Musse de chocolate a jato com manga e maracujá,doces,https://panelinha.com.br/receita/musse-chocola...,https://i.panelinha.com.br/i1/bk-1359-blog-ayu...,Esta é a musse de chocolate com o preparo mais...,"[[1 manga, 1 maracujá, 150 g de chocolate amar...",Panelinha,Pá-Pum,Até 4 porções,"[[Descasque e corte a manga em cubos de 1,5 cm...",{}
539,Creme batido,doces,https://panelinha.com.br/receita/creme-batido,https://i.panelinha.com.br/i1/bk-4819-receita-...,"Uma colherada de creme de leite no café, na to...",[[1 xícara (chá) de creme de leite fresco gela...,Panelinha,Pá-Pum,1 ¾ xícara (chá),[[Coloque o creme de leite gelado numa tigela ...,{}
540,Muffin de banana na Air Fryer Oven da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-banana...,https://i.panelinha.com.br/i1/bk-6546-16885056...,"As bananas cortadas em pedacinhos, a massa per...","[[2 bananas-prata maduras, 2 ovos, ½ xícara (c...",Panelinha,Pá-Pum,9 unidades,[[Unte com manteiga 9 forminhas médias para em...,{}

In [82]:
recipes_df.isnull().sum()

name           0
category       0
link           0
img            0
description    0
ingredients    0
author         0
time           0
serves         0
steps          0
nutrients      0
dtype: int64

In [83]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         541 non-null    object
 1   category     541 non-null    object
 2   link         541 non-null    object
 3   img          541 non-null    object
 4   description  541 non-null    object
 5   ingredients  541 non-null    object
 6   author       541 non-null    object
 7   time         541 non-null    object
 8   serves       541 non-null    object
 9   steps        541 non-null    object
 10  nutrients    541 non-null    object
dtypes: object(11)
memory usage: 46.6+ KB

In [84]:
recipes_df.describe()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
count,541,541,541,541,541,541,541,541,541,541,541
unique,384,1,384,384,383,383,14,4,105,384,1
top,Calda de chocolate com cachaça,doces,https://panelinha.com.br/receita/calda-de-choc...,https://i.panelinha.com.br/i1/bk-4879-calda-co...,Eles já são um ícone do Natal. A mistura de es...,"[[1 lata de leite condensado (395 g), 2 ovos, ...",Panelinha,Pá-Pum,Até 6 porções,[[Coloque todos os ingredientes numa panela pe...,{}
freq,4,541,4,4,4,4,519,175,99,4,541

In [85]:
recipes_df['name'].unique()

array(['Muffin de mirtilo na Air Fryer da Rita Lobo',
       'Muffin de maçã na Air Fryer da Rita Lobo',
       'Muffin de chocolate com laranja na Air Fryer da Rita Lobo',
       'Muffin de banana na Air Fryer da Rita Lobo',
       'Maçã assada na Air Fryer da Rita Lobo',
       'Bolo de iogurte com chá Earl Grey', 'Muffin de mirtilo',
       'Choux com chocolate e raspas de laranja',
       'Cobertura de bolo (ganache)', 'Bolinho de chocolate com ganache',
       'Doce de abóbora em pasta na panela de pressão elétrica',
       'Bolo flor de crepe com doce de leite', 'Crepe Suzette',
       'Pudim de chocolate', 'Ganache perfumada', 'Calda de mel',
       'Minipanetone com gotas de chocolate na Air Fryer da Rita Lobo',
       'Panetone com gotas de chocolate',
       'Torta de iogurte na Air Fryer da Rita Lobo',
       'Nhá Beth (merengue com chocolate)',
       'Pastel de goiabada com queijo na Air Fryer da Rita Lobo',
       'Pastel de banana com chocolate na Air Fryer da Rita Lobo',
       'Suflê de chocolate na Air Fryer da Rita Lobo',
       'Biscoito de castanha-do-pará', 'Éclair de Natal',
       'Cookie de banana com aveia e amendoim',
       'Barrinha de tâmara com cacau',
       'Bolo de caneca de maçã e amendoim (de micro-ondas)',
       'Bolo de caneca de banana com doce de leite',
       'Sequilho de polvilho', 'Chocolate quente com canela',
       'Pão doce de canela na Air Fryer da Rita Lobo',
       'Bolo de chocolate com gengibre',
       'Bolo de mandioca com coco na Air Fryer da Rita Lobo',
       'Geleia morna de frutas vermelhas com cardamomo', 'Amendoim doce',
       'Pipoca doce com chocolate', 'Pipoca doce com especiarias',
       'Pudim de Milho',
       'Bolinho de tapioca com coco e gengibre na Air Fryer da Rita Lobo',
       'Bolo de Fubá na Air Fryer da Rita Lobo',
       'Bolo de amêndoas com maçã na Air Fryer da Rita Lobo',
       'Pavlova com baba de moça', 'Cookie-brownie',
       'Bombom de sorvete de iogurte com framboesa',
       'Bombom de sorvete de café', 'Bombom de sorvete de doce de leite',
       'Bombom de sorvete', 'Rabanada na Air Fryer da Rita Lobo',
       'Minipanetone na Air Fryer da Rita Lobo',
       'Canjica na panela de pressão elétrica',
       'Brigadeirão na panela de pressão elétrica',
       'Cookie de abóbora e chocolate',
       'Crumble de banana com chocolate branco',
       'Trufinhas de chocolate com laranja e canela',
       'Crocante de gergelim', 'Pudim de tahine com crocante de gergelim',
       'Merengue de mel',
       'Banana assada na Air Fryer da Rita Lobo com merengue de mel',
       'Tarte tatin prática', 'Musse de chocolate de liquidificador',
       'Torta brookie', 'Bombocado na Air Fryer da Rita Lobo',
       'Biscoito de amêndoas (amaretti)',
       'Blondie com banana e castanha-de-caju',
       'Bolo invertido de abacaxi',
       'Bolinho de banana-da-terra com tapioca na Air Fryer da Rita Lobo',
       'Sorvete de iogurte com goiabada', 'Rocambole de laranja',
       'Brigadeiro de milho-verde', 'Pipoca doce',
       'Torrada de mel na Air Fryer da Rita Lobo', 'Torrada de mel',
       'Brownie na Air Fryer da Rita Lobo',
       'Pudim de panetone na panela de pressão elétrica',
       'Sagu de coco na panela de pressão elétrica',
       'Banana assada na Air Fryer da Rita Lobo',
       'Creme de confeiteiro com raspas de laranja e cardamomo',
       'Alecrim açucarado na Air Fryer da Rita Lobo',
       'Pavetone com pêssego',
       'Manjar de coco com calda de manga e maracujá',
       'Calda de manga e maracujá', 'Biscoito amanteigado de Natal',
       'Figo em calda na panela de pressão elétrica',
       'Broa recheada com creme de café',
       'Broa caxambu com doce de leite', 'Broa caxambu',
       'Broa brûlée (reaproveitamento)', 'Creme de confeiteiro',
       'Brownie de chocolate com café', 'Sorvete de cookie com leite',
       'Bolo de iogurte com limão',
       'Pudim de leite na panela de pressão elétrica',
       'Minipudim de leite',
       'Rabanada de pão de fôrma integral (reaproveitamento)',
       'Cheesecake com calda de damasco', 'Farofa de aveia',
       'Bolo de chocolate sem farinha',
       'Brownie de chocolate branco com matcha', 'Rabanada',
       'Rosca de reis', 'Semifredo de doce de leite com café',
       'Pé de moleque com semente de coentro', 'Boston cheesecake',
       'Calda de chocolate com cachaça',
       'Shortbread (biscoitos amanteigados)',
       'Ovo de Páscoa meio amargo com frutas secas',
       'Pudim de rabanada com peras carameladas', 'Creme inglês',
       'Creme batido perfumado', 'Bolo fudge de chocolate',
       'Uvas gratinadas',
       'Farofa doce de castanha-de-caju com raspas de laranja',
       'Crema catalana', 'Fondue de chocolate de micro-ondas',
       'Bombocado', 'Panqueca americana de chocolate (pancakes)',
       'Manga flambada com cachaça', 'Merengue com água de grão-de-bico',
       'Bolo de banana', 'Bolo de pamonha', 'Torta de figo',
       'Pudim de inhame', 'Biscoito de chocolate duplo',
       'Bolo delícia de limão', 'Torta de pêssego com amêndoas',
       'Biscoito de gengibre natalino', 'Musse de chocolate branco',
       'Baked Alaska de Panetone (reaproveitamento)',
       'Bolo de sorvete com coco e baba de moça', 'Blondie com amêndoas',
       'Bolo de cenoura com merengue e pistache',
       'Pudim de mandioca com cumaru (reaproveitamento)',
       'Trufas de chocolate',
       'Bolinho quente de doce de leite na Air Fryer da Rita Lobo',
       'Rabanada de arroz-doce', 'Panetone recheado com sorvete',
       'Sequilho', 'Palmier', 'Bolo musse de chocolate',
       'Bolo de curau cremoso',
       'Biscoitone (panetone coberto de chocolate)',
       'Doce de leite caseiro', 'Sorbet de manga',
       'Creme de abacate com sorvete', 'Gemada perfeita',
       'Musse de dois chocolates', 'Musse de chocolate',
       'Rocambole de doce de leite', 'Merengue italiano (marshmallow)',
       'Bolo de limão com glacê',
       'Bolo de sorvete com calda de frutas vermelhas',
       'Musse de morango', 'Biscoito de laranja', 'Pão de mel',
       'Torta de chocolate com damasco', 'Bolo floresta negra',
       'Granola na Air Fryer da Rita Lobo', 'Ovinhos de chocolate',
       'Pavlova na Air Fryer da Rita Lobo',
       'Suflê de goiabada com creme de mascarpone',
       'Biscoito de chocolate com castanha-do-pará',
       'Cobertura de cream cheese para bolos', 'Pavlova com frutas',
       'Pão de especiarias ao chocolate diet', 'Cocada branca',
       'Canjica com raspas de laranja e mel', 'Bolo de milho de caneca',
       'Malabie', 'Cookie com chocolate e castanha-de-caju',
       'Brigadeiro de micro-ondas', 'Bolo de chocolate com amendoim',
       'Compota de caju', 'Cocada da Paloma',
       'Sopa de manga e gengibre com frutas e sorvete de coco',
       'Torta prática de maçã verde', 'Petit gâteau de chocolate',
       'Ganache (cobertura ou recheio de bolo)', 'Biscoito de vinho',
       'Geleia de maçã com ameixa',
       'Casca de ovos para decorar e rechear',
       'Musse de chocolate a jato com manga e maracujá',
       'Muffin de banana na Air Fryer Oven da Rita Lobo', 'Creme batido',
       'Glacê festivo', 'Cuca de Uva', 'Doce de mamão verde',
       'Cocada mole', 'Amendoim açucarado', 'Sorvete de chá verde',
       'Tuiles de baunilha', 'Ambrosia rápida de leite em pó',
       'Espiral de banana caramelizada', 'Pudim de leite com furinhos',
       'Rocambole suflê de chocolate',
       'Sorvete de banana com cookies de aveia',
       'Kulfi de cenoura (sorvete indiano)',
       'Bolo perfeito de banana caramelada', 'Rabanadas com baunilha',
       'Musse de amora e cassis', 'Bolo em camadas de chocolate',
       'Quindão', 'Bagunça de morango com calda de cachaça',
       'Gratin des fruits', 'Pera picante com sorvete de canela',
       'Bolo de mel e maçã', 'Merengue suíço',
       'Abacaxi flambado com sorvete de coco',
       'Pêssego ao vinho com mascarpone',
       'Mont blanc - purê de castanhas', 'Pudim rápido de tapioca',
       'Crumble de aveia com maçã', 'Picolé de manga com iogurte',
       'Calda de chocolate', 'Calda de frutas vermelhas',
       'Calda de damasco', 'Torta de nozes', 'Baba de moça',
       'Bolo de chocolate com coco na caneca (de micro-ondas)',
       'Suflê de banana e laranja',
       'Tostex de banana com creme de avelã e chocolate',
       'Beijinho de colher', 'Pudim de pão integral com creme de avelã',
       'Pudim de leite sem furinhos',
       'Crème brûlée de gengibre ao perfume de laranja e baunilha',
       'Philo strudel', 'Bolo de mandioca cremoso com calda de coco',
       'Pé de moleque com laranja',
       'Bolo cremoso de chocolate com damasco e nozes',
       'Crepe com compota de morangos', 'Bombom de goiaba',
       'Muffin de amêndoas e passas', 'Sagu de café',
       'Crocante perfumado de castanha-de-caju',
       'Bolinho quente de doce de leite para dois', 'Torta de banana',
       'Sorvete de baunilha', 'Suflê de chocolate com calda de chocolate',
       'Crumble de uva com maçã', 'Tigelinhas de suspiro com maracujá',
       'Sopa de capim-santo com papaia',
       'Morango flambado com sorvete de creme', 'Waffle (favo holandês)',
       'Manjar de coco', 'Compota de chuchu com frutas e vinho',
       'Bolo de maçã com farofa de coco',
       'Batata-doce em calda com merengue', 'Cookie com sorvete e café',
       'Sagu de coco com manga grelhada', 'Pamonha com coco',
       'Crumble de pera com frutas vermelhas',
       'Rosca doce de cenoura com ameixa',
       'Morango com creme batido e água de rosas',
       'Geleia de morango com maracujá', 'Cuscuz de tapioca com coco',
       'Zuppa Inglese (reaproveitamento)', 'Creme de abacate congelado',
       'Curau', 'Bolo de aniversário dos meus filhos',
       'Rocambole (pão de ló com fécula de batata)',
       'Affogato (café com sorvete)',
       'Abacaxi grelhado com licor de laranja',
       'Bolo de crepe com geleia de morango e maracujá',
       'Brownie cremoso de castanha-do-pará',
       'Rocambole com geleia de framboesa', 'Biscoito 1 2 3',
       'Brigadeiro de tahine (de micro-ondas)',
       'Rabanadas com licor de laranja',
       'Creme de papaia congelado com licor de cassis',
       'Bolo inglês clássico (Pound cake)', 'Bolo inglês com frutas',
       'Tartine de maçã com mel e canela',
       'Iogurte com berries e suspiros no pote',
       'Panqueca americana de banana-da-terra', 'Tarte tatin',
       'Musse de chocolate com café', 'Massa para torta doce',
       'Gemada com vinho do Porto', 'Zabaione com folhas de chocolate',
       'Crumble de peras ao vinho',
       'Babka com brigadeiro de canela e laranja', 'Torta quente de maçã',
       'Submarino de chocolate',
       'Arroz-doce com especiarias (cúrcuma, cardamomo e canela)',
       'Brigadeiro tradicional',
       'Brigadeiro de micro-ondas com chocolate amargo',
       'Crocante de pêssego', 'Crumble de abóbora', 'Pastel de banana',
       'Maçã do amor', 'Sonho', 'Biscoito de marzipã',
       'Gomos de laranja macerados', 'Leite condensado caseiro',
       'Ovo de Páscoa meio amargo', 'Manteiga de maçã (apple butter)',
       'Panacota de café', 'Crepe de morango',
       'Polenta doce com peras ao vinho', 'Rabanada brûlée em palitos',
       'Raspadinha de mamão com gengibre', 'Cocada de forno',
       'Biscoitos amanteigados',
       'Arroz-doce com macerado de ameixa e vinho do Porto',
       'Bolo de Paçoca', 'Arroz-doce perfumado com cardamomo',
       'Biscoito de gengibre', 'Brigadeiro de abóbora e amêndoas',
       'Pavlova tropical', 'Arroz-doce cremoso', 'Brigadeiro de colher',
       'Arroz-doce na panela de pressão elétrica',
       'Arroz-doce com calda de caramelo e flor de sal',
       'Arroz-doce tradicional', 'Bolo cremoso de chocolate',
       'Creme brûlée com lavanda', 'Ricota com minipera grelhada',
       'Bolo de cenoura com especiarias (carrot cake)',
       'Tarte tatin de frigideira',
       'Bolinho de chuva de abóbora com chocolate',
       'Concord - bolo suspiro', 'Bombom de damasco e amêndoas',
       'Cuscuz de tapioca de colher', 'Bolo de amêndoa com coco e uva',
       'Geleia de jabuticaba', 'Suflê de goiabada com requeijão',
       'Pudim de leite na Air Fryer da Rita Lobo',
       'Cocadinha francesa (reaproveitamento)',
       'Brownie rústico com cardamomo', 'Macarons',
       'Gelatina de vinho branco com especiarias', 'Creme de chantilly',
       'Sorvete de banana', 'Pera cozida no micro-ondas com mel e canela',
       'Bolo gelado de abacaxi', 'Torta de ricota com pêssegos macerados',
       'Bolo de laranja', 'Brownie da Maguy',
       'Doce de cenoura indiano (Gajar ka halwa)',
       'Frutas cozidas ao curry', 'Papo de anjo', 'Cuca de banana',
       'Bolinho de chocolate com castanha-de-caju e mel', 'Manjar branco',
       'Bolo de sorvete com calda de caramelo', 'Crème brûlée',
       'Doce de leite de corte',
       'Salada de frutas primaveril com cachaça',
       'Banana dourada com merengue',
       'Pudim de tapioca com calda de coco queimado', 'Banana flambada',
       'Suflê de chocolate', 'Biscoitão de frigideira',
       'Panetone com frutas e sorvete', 'Ovo de Páscoa ao leite pintado',
       'Salada de frutas ao vinho', 'Ovinhos pintados',
       'Batata-doce ao leite de coco',
       'Torta de banana com nozes e especiarias',
       'Geleia de pêssego com chuchu e vinho',
       'Banana caramelada com suspiro',
       'Musse que vira suflê (de véspera)',
       'Sorvete de chocolate com amêndoas', 'Pain perdu de challah',
       'Banana foster', 'Chremslach', 'Brigadeiro de panela', 'Bolo-rei',
       'Manga grelhada com sorvete de banana',
       'Rabanada de pão de fôrma com raspas de laranja',
       'Bolo de fubá com limão e castanha-de-caju',
       'Bolo de banana com uva-passa', 'Peras assadas no micro-ondas',
       'Rolinhos de canela', 'Pera com especiarias e calda de chocolate',
       'Barra de aveia e maçã', 'Sacolé de iogurte com coco',
       'Lemon curd', 'Pudim de doce de leite',
       'Tarte tatin individual de abacaxi',
       'Musse de iogurte com calda de abacaxi',
       'Musse de limão-siciliano', 'Geleia de morango',
       'Torta de castanha-de-caju e damasco'], dtype=object)

In [86]:
len(recipes_df['name'].unique())

384

In [87]:
recipes_df.name.value_counts()

name
Calda de chocolate com cachaça             4
Bolo perfeito de banana caramelada         3
Kulfi de cenoura (sorvete indiano)         3
Sorvete de banana com cookies de aveia     3
Rocambole suflê de chocolate               3
                                          ..
Batata-doce ao leite de coco               1
Torta de banana com nozes e especiarias    1
Manjar branco                              1
Bolo de sorvete com calda de caramelo      1
Crème brûlée                               1
Name: count, Length: 384, dtype: int64

In [88]:
# recipes_df.loc[recipes_df['name'] == 'Bolo perfeito de banana caramelada']
recipes_df[recipes_df['name'] == 'Bolo perfeito de banana caramelada']

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
232,Bolo perfeito de banana caramelada,doces,https://panelinha.com.br/receita/bolo-perfeito...,https://i.panelinha.com.br/i1/bk-4571-ep-13-ba...,Um bolo que perfuma a casa toda antes mesmo de...,"[[1 xícara (chá) de açúcar, ½ xícara (chá) de ...",Panelinha,Até 2h,Mais de 6 porções,"[[Descasque e divida cada banana em 3 fatias, ...",{}
243,Bolo perfeito de banana caramelada,doces,https://panelinha.com.br/receita/bolo-perfeito...,https://i.panelinha.com.br/i1/bk-4571-ep-13-ba...,Um bolo que perfuma a casa toda antes mesmo de...,"[[1 xícara (chá) de açúcar, ½ xícara (chá) de ...",Panelinha,Até 2h,Mais de 6 porções,"[[Descasque e divida cada banana em 3 fatias, ...",{}
469,Bolo perfeito de banana caramelada,doces,https://panelinha.com.br/receita/bolo-perfeito...,https://i.panelinha.com.br/i1/bk-4571-ep-13-ba...,Um bolo que perfuma a casa toda antes mesmo de...,"[[1 xícara (chá) de açúcar, ½ xícara (chá) de ...",Panelinha,Até 2h,Mais de 6 porções,"[[Descasque e divida cada banana em 3 fatias, ...",{}

In [89]:
recipes_df.groupby('name').groups

{'Abacaxi flambado com sorvete de coco': [249, 489], 'Abacaxi grelhado com licor de laranja': [303], 'Affogato (café com sorvete)': [302], 'Alecrim açucarado na Air Fryer da Rita Lobo': [78], 'Ambrosia rápida de leite em pó': [226, 498], 'Amendoim açucarado': [219, 505], 'Amendoim doce': [35], 'Arroz-doce com calda de caramelo e flor de sal': [354], 'Arroz-doce com especiarias (cúrcuma, cardamomo e canela)': [325], 'Arroz-doce com macerado de ameixa e vinho do Porto': [345], 'Arroz-doce cremoso': [351], 'Arroz-doce na panela de pressão elétrica': [353], 'Arroz-doce perfumado com cardamomo': [347], 'Arroz-doce tradicional': [355], 'Baba de moça': [259], 'Babka com brigadeiro de canela e laranja': [322], 'Bagunça de morango com calda de cachaça': [237, 463], 'Baked Alaska de Panetone (reaproveitamento)': [142, 156, 382], 'Banana assada na Air Fryer da Rita Lobo': [76], 'Banana assada na Air Fryer da Rita Lobo com merengue de mel': [58], 'Banana caramelada com suspiro': [482], 'Banana dourada com merengue': [455], 'Banana flambada': [457], 'Banana foster': [486], 'Barra de aveia e maçã': [521], 'Barrinha de tâmara com cacau': [26], 'Batata-doce ao leite de coco': [479], 'Batata-doce em calda com merengue': [288], 'Beijinho de colher': [263], 'Biscoito 1 2 3': [307], 'Biscoito amanteigado de Natal': [82], 'Biscoito de amêndoas (amaretti)': [63], 'Biscoito de castanha-do-pará': [23], 'Biscoito de chocolate com castanha-do-pará': [184, 204, 518], 'Biscoito de chocolate duplo': [137, 411], 'Biscoito de gengibre': [348], 'Biscoito de gengibre natalino': [140, 155, 381], 'Biscoito de laranja': [173, 388], 'Biscoito de marzipã': [333], 'Biscoito de vinho': [208, 533], 'Biscoitone (panetone coberto de chocolate)': [160, 386], 'Biscoitos amanteigados': [344], 'Biscoitão de frigideira': [459], 'Blondie com amêndoas': [144, 371], 'Blondie com banana e castanha-de-caju': [64], 'Bolinho de banana-da-terra com tapioca na Air Fryer da Rita Lobo': [66], 'Bolinho de chocolate com castanha-de-caju e mel': [440], 'Bolinho de chocolate com ganache': [9], 'Bolinho de chuva de abóbora com chocolate': [361], 'Bolinho de tapioca com coco e gengibre na Air Fryer da Rita Lobo': [39], 'Bolinho quente de doce de leite na Air Fryer da Rita Lobo': [148, 374], 'Bolinho quente de doce de leite para dois': [276], 'Bolo cremoso de chocolate': [356], 'Bolo cremoso de chocolate com damasco e nozes': [270], 'Bolo de Fubá na Air Fryer da Rita Lobo': [40], 'Bolo de Paçoca': [346], 'Bolo de amêndoa com coco e uva': [366], 'Bolo de amêndoas com maçã na Air Fryer da Rita Lobo': [41], 'Bolo de aniversário dos meus filhos': [300], 'Bolo de banana': [130, 418], 'Bolo de banana com uva-passa': [496], 'Bolo de caneca de banana com doce de leite': [28], 'Bolo de caneca de maçã e amendoim (de micro-ondas)': [27], 'Bolo de cenoura com especiarias (carrot cake)': [359], 'Bolo de cenoura com merengue e pistache': [145, 364], 'Bolo de chocolate com amendoim': [194, 224, 500], 'Bolo de chocolate com coco na caneca (de micro-ondas)': [260], 'Bolo de chocolate com gengibre': [32], 'Bolo de chocolate sem farinha': [97, 115, 429], 'Bolo de crepe com geleia de morango e maracujá': [304], 'Bolo de curau cremoso': [159, 385], 'Bolo de fubá com limão e castanha-de-caju': [495], 'Bolo de iogurte com chá Earl Grey': [5], 'Bolo de iogurte com limão': [91], 'Bolo de laranja': [434], 'Bolo de limão com glacê': [170, 400], 'Bolo de mandioca com coco na Air Fryer da Rita Lobo': [33], 'Bolo de mandioca cremoso com calda de coco': [268], 'Bolo de maçã com farofa de coco': [287], 'Bolo de mel e maçã': [247, 473], 'Bolo de milho de caneca': [190, 198, 512], 'Bolo de pamonha': [131, 417], 'Bolo de sorvete com calda de caramelo': [442], 'Bolo de sorvete com calda de frutas vermelhas': [171, 399], 'Bolo de sorvete com coco e baba de moça': [143, 152, 378], 'Bolo delícia de limão': [138, 410], 'Bolo em camadas de chocolate': [235, 461], 'Bolo flor de crepe com doce de leite': [11], 'Bolo floresta negra': [176, 391], 'Bolo fudge de chocolate': [119, 444], 'Bolo gelado de abacaxi': [432], 'Bolo inglês clássico (Pound cake)': [311], 'Bolo inglês com frutas': [312], 'Bolo invertido de abacaxi': [65], 'Bolo musse de chocolate': [158, 384], 'Bolo perfeito de banana caramelada': [232, 243, 469], 'Bolo-rei': [492], 'Bombocado': [124, 182, 452], 'Bombocado na Air Fryer da Rita Lobo': [62], 'Bombom de damasco e amêndoas': [363], ...}

In [90]:
# recipes_df.groupby('name')['name'].size().sort_values(ascending=False)
recipes_df.groupby('name')['name'].count().sort_values(ascending=False)

name
Calda de chocolate com cachaça                4
Biscoito de chocolate com castanha-do-pará    3
Panqueca americana de chocolate (pancakes)    3
Biscoito de gengibre natalino                 3
Compota de caju                               3
                                             ..
Cocadinha francesa (reaproveitamento)         1
Cocada de forno                               1
Cobertura de bolo (ganache)                   1
Chremslach                                    1
Cookie-brownie                                1
Name: name, Length: 384, dtype: int64

In [91]:
res = (recipes_df.groupby('name')['name'].count()>1).values
res

array([ True, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True,  True, False,  True,  True, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False, False,  True, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
       False, False, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False,  True, False, False,  True, False, False, False, False,
        True,  True,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True, False, False, False,
        True, False, False, False, False, False,  True,  True, False,
        True,  True, False,  True, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False,  True,  True,
        True,  True, False, False,  True, False, False,  True, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True,  True, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False,  True, False, False, False,  True,  True, False, False,
        True,  True,  True,  True, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False,  True, False, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False,  True, False,
        True,  True, False, False, False, False])

In [92]:
recipes_df.duplicated(subset=['name', 'link'])

0      False
1      False
2      False
3      False
4      False
       ...
536     True
537     True
538     True
539     True
540     True
Length: 541, dtype: bool

In [93]:
recipes_df.duplicated(subset=['name', 'link']).sum()

np.int64(157)

In [94]:
recipes_df = recipes_df.drop_duplicates(subset=['name', 'link'], keep='first', ignore_index=True)
recipes_df.describe()

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
count,384,384,384,384,384,384,384,384,384,384,384
unique,384,1,384,384,383,383,14,4,105,384,1
top,Bolo-rei,doces,https://panelinha.com.br/receita/bolo-de-reis,https://i.panelinha.com.br/i1/bk-3943-bolo-de-...,Eles já são um ícone do Natal. A mistura de es...,"[[1 lata de leite condensado (395 g), 2 ovos, ...",Panelinha,Pá-Pum,Até 6 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
freq,1,384,1,1,2,2,369,123,70,1,384

In [95]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         384 non-null    object
 1   category     384 non-null    object
 2   link         384 non-null    object
 3   img          384 non-null    object
 4   description  384 non-null    object
 5   ingredients  384 non-null    object
 6   author       384 non-null    object
 7   time         384 non-null    object
 8   serves       384 non-null    object
 9   steps        384 non-null    object
 10  nutrients    384 non-null    object
dtypes: object(11)
memory usage: 33.1+ KB

In [131]:
recipes_df.to_json('panelinha_dessert_recipes_cleaned.json', orient='records', indent=4)
recipes_df.head(7)

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients
0,Muffin de mirtilo na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-9355-blog-muf...,Mirtilo e limão-siciliano são uma dupla e tant...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{}
1,Muffin de maçã na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mac...,https://i.panelinha.com.br/i1/bk-3626-blog-muf...,O melhor deste muffin está no contraste: a mas...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{}
2,Muffin de chocolate com laranja na Air Fryer d...,doces,https://panelinha.com.br/receita/muffin-de-cho...,https://i.panelinha.com.br/i1/bk-1389-blog-muf...,"Nesta receita, gotas de chocolate derretem na ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{}
3,Muffin de banana na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-ban...,https://i.panelinha.com.br/i1/bk-3625-blog-muf...,"Banana e canela deixam a massa macia, úmida e ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{}
4,Maçã assada na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/maca-assada-n...,https://i.panelinha.com.br/i1/bk-5932-blog-mac...,"Maçã, canela, mel e Air Fryer: com poucos ingr...","[[1 maçã (fuji ou gala), 2 colheres (chá) de m...",Panelinha,Pá-Pum,Até 2 porções,"[[Lave, seque e corte a maçã ao meio no sentid...",{}
5,Bolo de iogurte com chá Earl Grey,doces,https://panelinha.com.br/receita/bolo-de-iogur...,https://i.panelinha.com.br/i1/bk-5319-blog-bol...,"Perfumado e fofinho, este bolo leva chá Earl G...",[[1 xícara (chá) de iogurte natural sem açúcar...,Panelinha,Até 1h,12 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{}
6,Muffin de mirtilo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-7970-blog-muf...,O sucesso deste muffin está no contraste de te...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Até 1h,9 unidades,"[[Numa tigela, misture os ingredientes com a p...",{}

In [97]:
ingredients = recipes_df[recipes_df.name == 'Choux com chocolate e raspas de laranja']['ingredients'].items()
for ingredient in ingredients:
    print(ingredient[1])

[['50 g de manteiga em ponto pomada', '⅓ de xícara (chá) de açúcar demerara', '½ xícara (chá) de farinha de trigo'], ['½ xícara (chá) de farinha de trigo peneirada', '½ xícara (chá) de chocolate 55% cacau em gotas (cerca de 90 g)', '¼ de xícara (chá) de leite', '¼ de xícara (chá) de água', '5 colheres (sopa) de manteiga (cerca de 60g)', '1 colher (chá) de açúcar', '¼ de colher (chá) de sal', '2 ovos', 'raspas de 1 laranja-baía']]

In [98]:
ingredients = []
for x in recipes_df[recipes_df.name == 'Choux com chocolate e raspas de laranja']['ingredients'].explode().array:
   ingredients.extend(x) 
ingredients_dict = {'name': 'Choux com chocolate e raspas de laranja', 'ingredients': ingredients}
ingredients_df = pd.DataFrame(ingredients_dict)
ingredients_df

,name,ingredients
0,Choux com chocolate e raspas de laranja,50 g de manteiga em ponto pomada
1,Choux com chocolate e raspas de laranja,⅓ de xícara (chá) de açúcar demerara
2,Choux com chocolate e raspas de laranja,½ xícara (chá) de farinha de trigo
3,Choux com chocolate e raspas de laranja,½ xícara (chá) de farinha de trigo peneirada
4,Choux com chocolate e raspas de laranja,½ xícara (chá) de chocolate 55% cacau em gotas...
5,Choux com chocolate e raspas de laranja,¼ de xícara (chá) de leite
6,Choux com chocolate e raspas de laranja,¼ de xícara (chá) de água
7,Choux com chocolate e raspas de laranja,5 colheres (sopa) de manteiga (cerca de 60g)
8,Choux com chocolate e raspas de laranja,1 colher (chá) de açúcar
9,Choux com chocolate e raspas de laranja,¼ de colher (chá) de sal
10,Choux com chocolate e raspas de laranja,2 ovos
11,Choux com chocolate e raspas de laranja,raspas de 1 laranja-baía

In [99]:
ingredients_df = recipes_df[['name', 'ingredients']].copy()
ingredients_df = ingredients_df.explode('ingredients').explode('ingredients')
ingredients_df

,name,ingredients
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 colher (sopa) de manteiga gelada
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de açúcar
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de farinha de trigo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,¾ de xícara (chá) de mirtilo (cerca de 125 g)
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 xícara (chá) de farinha de trigo
...,...,...
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar
383,Torta de castanha-de-caju e damasco,2 ovos
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...
383,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...
383,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho

In [100]:
import spacy
import pt_core_news_sm

nlp = spacy.load('pt_core_news_sm')

In [101]:
nlp.get_pipe('ner').labels

('LOC', 'MISC', 'ORG', 'PER')

In [102]:
print(spacy.explain('LOC'))
print(spacy.explain('MISC'))
print(spacy.explain('ORG'))
print(spacy.explain('PER'))

Non-GPE locations, mountain ranges, bodies of water
Miscellaneous entities, e.g. events, nationalities, products or works of art
Companies, agencies, institutions, etc.
Named person or family.

In [103]:
items = ingredients_df.head(20)['ingredients'].values
text = '\n'.join(items)
print(text)
doc = nlp(text)
for ent in doc.ents:
    print(f'{ent.text} -> {ent.label_}')

1 colher (sopa) de manteiga gelada
2 colheres (sopa) de açúcar
2 colheres (sopa) de farinha de trigo
¾ de xícara (chá) de mirtilo (cerca de 125 g)
1 xícara (chá) de farinha de trigo
¾ de xícara (chá) de açúcar
1 colher (chá) de fermento em pó
raspas de 1 limão-siciliano
1 ovo
⅓ de xícara (chá) de iogurte natural sem açúcar nem adoçante
50 g de manteiga
manteiga e farinha de trigo para untar e polvilhar as forminhas
1 colher (sopa) de manteiga gelada
2 colheres (sopa) de açúcar
2 colheres (sopa) de farinha de trigo
1 minimaçã
1 xícara (chá) de farinha de trigo
¾ de xícara (chá) de açúcar
1 colher (chá) de fermento em pó
2 bagas de cardamomo
⅓ -> MISC

In [104]:
spacy.displacy.render(doc, style='ent', jupyter=True)

In [105]:
ingredients_df

,name,ingredients
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 colher (sopa) de manteiga gelada
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de açúcar
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de farinha de trigo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,¾ de xícara (chá) de mirtilo (cerca de 125 g)
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 xícara (chá) de farinha de trigo
...,...,...
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar
383,Torta de castanha-de-caju e damasco,2 ovos
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...
383,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...
383,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho

In [106]:
ingredients_df[ingredients_df['ingredients'].astype(str).str.contains(r'\bkg\b', case=False, na=False)]

,name,ingredients
10,Doce de abóbora em pasta na panela de pressão ...,1 kg de abóbora de pescoço descascada
106,Ovo de Páscoa meio amargo com frutas secas,1 kg de chocolate meio amargo
133,Trufas de chocolate,1 kg de chocolate meio amargo
186,Doce de mamão verde,1 kg de mamão verde
186,Doce de mamão verde,"1,5 kg de açúcar"
209,Mont blanc - purê de castanhas,1 kg de castanha portuguesa
287,Crumble de abóbora,1 kg de abóbora de pescoço descascada
295,Manteiga de maçã (apple butter),1 kg de maçã fuji (4 a 5 unidades)
324,Geleia de jabuticaba,1 kg de jabuticaba
354,Ovo de Páscoa ao leite pintado,1 kg de chocolate ao leite
357,Batata-doce ao leite de coco,1 kg de batata-doce
378,Pudim de doce de leite,1 kg de açúcar

In [107]:
import re
import pandas as pd

# Extract likely measurement units from ingredient strings
standard_measure_pattern = re.compile(r"\b(?:grama|gramas|kg|g|ml|l|oz|lbs|mg|cm|mm|m)\b", re.IGNORECASE)
household_unit_pattern = re.compile(r"\b(?:xícara|xícaras|colher|colheres|copo|copos|pitada|pitadas|pacote|pacotes|envelope|envelopes|unidade|unidades|lata|latas|pedaço|pedaços|fatia|fatias|tbsp|tsp|cup|cups|caixa|caixas)\b(?:\s*\((?:chá|sopa)\))?", re.IGNORECASE)

units = []
for value in ingredients_df['ingredients'].dropna():
    units.extend(standard_measure_pattern.findall(str(value)))

sorted_units = sorted({u.lower() for u in units})
print(f'{sorted_units}')
print(f'{len(sorted_units)} unique standard measurement units found in the ingredients.')

['cm', 'g', 'kg', 'ml']
4 unique standard measurement units found in the ingredients.

In [108]:
import unicodedata

In [109]:
def convert_vulgar_fraction(text):
    text = list(text)
    fractions = [(i, unicodedata.normalize("NFKC", char)) for i, char in enumerate(text) if 'VULGAR FRACTION' in unicodedata.name(char)]
    if len(fractions) > 0:
        for pos, normalized_fraction in fractions:
            text[pos] = normalized_fraction
    return ''.join(text)

def remove_verbose(text):
    adjectives = '((grand|fort|fervent|quent|firm)(es|e))|(?:(?:pequen|médi|variad|debulhad|peneirad|filtrad|morn|derretid|congelad|gelad|refrigerad|fri|amanhecid|madur|preparad|amassad|triturad|quebrad|ralad|picad|descascad|lavad|cortad|coad|fin|gross)(?:as|a|os|o))'
    instructions = 'para\s+(?:caramelizar|enrolar|pincelar|polvilhar|untar|decorar|fritar|passar|hidratar|assar|dourar|servir|prensa)|na hora'
    modes = 'bem(?:\s+\w+)*|de\s+preferência|a\s+gosto|o\s+quanto\s+baste|sem sementes|sem semente|em\s+(?:(?:cub|palit|pedac|pedaç)(?:inhos|inho|os|o)|(?:temperatura ambiente|ponto(?:\s+de)?\s+pomada|(?:(?:gota|grão|tira)(?:s)?)|callets|pasta|lata))|(?:com\s+palha)'

    adjectives_regex = fr'\b({adjectives}\,?)'
    for adj in re.finditer(adjectives_regex, text):
        text = re.sub(adj.group(1), '#', text, re.IGNORECASE)

    modes_regex = fr'(\b{modes}\,?)'
    for mode in re.finditer(modes_regex, text):
        text = re.sub(mode.group(1), '#', text, re.IGNORECASE)

    instructions_regex = fr'(\b{instructions})'
    for instruction in re.finditer(instructions_regex, text):
        text = re.sub(instruction.group(1), '#', text, re.IGNORECASE)

    text = re.sub(r'(\s+\#((\s+\d+\%?)|(\s+\w+))*)+|^(\#\s+)*', '', text, re.IGNORECASE).strip()
    
    miscellaneous_regex = '((cubos|cubo)\s+de\s+)|((tiras|tira|sobras|sobra)\s*((de|da)\s+)?)|(generos(as|os|a|o)\s+(de\s+)?)|((\s+com)?\s+cerca\s+de)$|(\s+e$)|\,$|^(de\s+)|^(da\s+)|^(do\s+)|(\s+de)$|receita\s+de\s+'
    text = re.sub(miscellaneous_regex, '', text, re.IGNORECASE).strip()

    utensils_regex = '(^(fôrm|form|canud|pincel|papel-manteiga)\w*)(\s+\w+)*'
    text = re.sub(utensils_regex, '', text, re.IGNORECASE).strip()

    items = re.sub(r'(\,\s+(?!torrad))|(\s+\be\b\s+(?!(sem|torrad|moíd)))|(\s+\bou\b\s+(?!de))', '#', text)

    if items == '':
        return []

    return items.split('#')

def clean_ingredient_description(description):
    description = re.sub(
        household_measure_pattern, 
        '', 
        re.sub(standard_measure_pattern, '', 
               re.sub(informal_measure_pattern, '', description)
        )
    ).strip()
    description = re.sub(r'^de\s+|(\s+de|\s+ou)$', '', description)
    description = re.sub(fr'\s*\((\w+\s+)*({quantity_regex})?(\s+\w*\-?\,?)*\)\s*', '', description)
    description = re.sub(fr'\s+\((cerca)?((\s+\w+)*|{household_measure_regex}|(\s+\+\s+))\s*\)', '', description)
    description = re.sub(fr'\s*\((\,\s+)?(((\w+(\-\w+)?)|(\d+\%?))\,?\.*\:?\s*)*\)', '', description)
    description = re.sub(r'(\s*\+\s*(de)?\s*)*', '', description)
    description = re.sub(r'\s*\((\s*\/\s*\d*)(\s+\w+)*\s*\)', '', description)
    description = re.sub(fr'\s*{quantity_regex}\s*(cm|mm|m)\b(\s+\w+)*', '', description)

    if re.search(unit_pattern, description):
        desc = re.sub(quantity_regex, '##', description)
        parts = re.split('##', desc)
        if parts[0] == '':
            description = [
                re.sub(
                    r'^de\s+', 
                    '', 
                    parts.pop().strip()
                )
            ]
        else:
            description = [parts[0].strip(), parts.pop().strip()]

    if type(description) != list:
        description = [description]
    
    return description

In [110]:
ingredients_df['ingredients_fractional'] = ingredients_df['ingredients'].apply(lambda x: convert_vulgar_fraction(x))

standard_measures = 'grama|gramas|kg|g|litros|litro|ml|l|oz|lbs|mg'
household_measures = 'xícaras|xícara|colheres|colher|copos|copo|potes|pote|pitadas|pitada|pacotes|pacote|envelopes|envelope|unidades|unidade|latas|lata|pedaços|pedaço|fatias|fatia|tabletes|tablete|saquinhos|saquinho|tbsp|tsp|cups|cup|caixas|caixa|bolas|bola'
informal_measures = 'dúzias|dúzia|pencas|penca|espigas|espiga|bagas|baga|gotas|gota|ramas|rama|ramos|ramo|cachos|cacho|metades|metade|cavidades|cavidade'

quantity_regex = '(?P<quantity>(\d+\s+\d+\N{FRACTION SLASH}\d+|\d+\N{FRACTION SLASH}\d+|\d+(?!\s+\d+))(\.\d+|\,\d+)?)'

standard_measure_regex = fr'\b{quantity_regex}(?:\s*)(?P<measure>{standard_measures})\b'
household_measure_regex = fr'{quantity_regex}(?:\s*\w*\s*)(?P<measure>(?:{household_measures})((\s*\((chá|sopa)\))|(\s*\[(chá|sopa)\]))?)'
informal_measure_regex = fr'{quantity_regex}\s+(?P<measure>{informal_measures})\b'
unit_regex = f'\s*{quantity_regex}\s+(?!(?:de\s+)?(?:{household_measures}|{standard_measures}|{informal_measures}|cm|mm|m)(?:\s+|\,|\)))'

standard_measure_pattern = re.compile(
    fr'{standard_measure_regex}', 
    flags=re.IGNORECASE
)
household_measure_pattern = re.compile(
    fr'{household_measure_regex}',
    flags=re.IGNORECASE
)
informal_measure_pattern = re.compile(
    fr'{informal_measure_regex}',
    flags=re.IGNORECASE
)
unit_pattern = re.compile(
    fr'{unit_regex}', 
    re.IGNORECASE
)

def create_entities(text):
    entities = {'entities': []}

    standard_matches = standard_measure_pattern.finditer(text)
    for match in standard_matches:
        entities['entities'].append((match.start('quantity'), match.end('measure'), 'MEDIDA_PADRAO'))

    household_matches = household_measure_pattern.finditer(text)
    for match in household_matches:
        entities['entities'].append((match.start('quantity'), match.end('measure'), 'MEDIDA_CASEIRA'))

    informal_matches = informal_measure_pattern.finditer(text)
    for match in informal_matches:
        entities['entities'].append((match.start('quantity'), match.end('measure'), 'MEDIDA_INFORMAL'))

    unit_matches = unit_pattern.finditer(text)
    for match in unit_matches:
        entities['entities'].append((match.start('quantity'), match.end('quantity'), 'UNIDADE'))

    ingredient = clean_ingredient_description(text)
    ingredient_only = ''
    for part in ingredient:
        part = remove_verbose(part)
        for item in part:
            item_part_match = re.search(re.escape(item), text)
            if item_part_match:
                entities['entities'].append((item_part_match.start(), item_part_match.end(), 'ALIMENTO'))
                ingredient_only += item + " "        

    entities['entities'].sort(key=lambda x: x[0])
    return entities, ingredient_only.strip()

ingredients_df['entity_food'] = ingredients_df['ingredients_fractional'].map(create_entities)
ingredients_df['entity'] = ingredients_df['entity_food'].map(lambda entity_food: entity_food[0])
ingredients_df['food'] = ingredients_df['entity_food'].map(lambda entity_food: entity_food[1])
ingredients_df.drop(columns=['entity_food'], inplace=True)
ingredients_df

,name,ingredients,ingredients_fractional,entity,food
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 colher (sopa) de manteiga gelada,1 colher (sopa) de manteiga gelada,"{'entities': [(0, 15, 'MEDIDA_CASEIRA'), (19, ...",manteiga
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de açúcar,2 colheres (sopa) de açúcar,"{'entities': [(0, 17, 'MEDIDA_CASEIRA'), (21, ...",açúcar
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de farinha de trigo,2 colheres (sopa) de farinha de trigo,"{'entities': [(0, 17, 'MEDIDA_CASEIRA'), (21, ...",farinha de trigo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,¾ de xícara (chá) de mirtilo (cerca de 125 g),3⁄4 de xícara (chá) de mirtilo (cerca de 125 g),"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, ...",mirtilo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 xícara (chá) de farinha de trigo,1 xícara (chá) de farinha de trigo,"{'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, ...",farinha de trigo
...,...,...,...,...,...
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar,1⁄2 xícara (chá) de açúcar,"{'entities': [(0, 16, 'MEDIDA_CASEIRA'), (20, ...",açúcar
383,Torta de castanha-de-caju e damasco,2 ovos,2 ovos,"{'entities': [(0, 1, 'UNIDADE'), (2, 6, 'ALIME...",ovos
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...,1⁄2 xícara (chá) de castanha-de-caju torrada s...,"{'entities': [(0, 16, 'MEDIDA_CASEIRA'), (20, ...",castanha-de-caju torrada sem sal
383,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...,2⁄3 de xícara (chá) de damasco seco cortado em...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, ...",damasco seco
383,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho,1 colher (chá) de amido de milho,"{'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, ...",amido de milho

In [111]:
ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'\d+\s+\d+(?:\N{FRACTION SLASH}\d+)?')]

,name,ingredients,ingredients_fractional,entity,food
38,Pudim de Milho,2 latas de milho-verde (cerca de 2 ¼ xícaras [...,2 latas de milho-verde (cerca de 2 1⁄4 xícaras...,"{'entities': [(0, 7, 'MEDIDA_CASEIRA'), (11, 2...",milho-verde
144,Creme de abacate com sorvete,caldo de 1 ½ limão,caldo de 1 1⁄2 limão,"{'entities': [(0, 5, 'ALIMENTO'), (9, 14, 'UNI...",caldo limão
237,Suflê de chocolate com calda de chocolate,⅓ de xícara (chá) + 1 ½ colher (sopa) de açúca...,1⁄3 de xícara (chá) + 1 1⁄2 colher (sopa) de a...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (22, ...",açúcar
265,Biscoito 1 2 3,300 g de farinha de trigo ou 2 ½ xícaras (chá),300 g de farinha de trigo ou 2 1⁄2 xícaras (chá),"{'entities': [(0, 5, 'MEDIDA_PADRAO'), (9, 25,...",farinha de trigo
293,Leite condensado caseiro,320 g de açúcar demerara (ou cristal) (1 ½ xíc...,320 g de açúcar demerara (ou cristal) (1 1⁄2 x...,"{'entities': [(0, 5, 'MEDIDA_PADRAO'), (9, 24,...",açúcar demerara
317,Bolo de cenoura com especiarias (carrot cake),2 cenouras (cerca de 240g ou 1 ½ xícara (chá) ...,2 cenouras (cerca de 240g ou 1 1⁄2 xícara (chá...,"{'entities': [(0, 1, 'UNIDADE'), (2, 10, 'ALIM...",cenouras

In [112]:
# ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'cachos|cacho|pencas|penca|dúzias|dúzia|bagas|baga')]
# ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'((\be\b)|(\bou\b(?!\s+de)))(?!\s+(sem|torrad|moíd))')]
# ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'\s+(cm|mm|m)\b')]
ingredients_df[ingredients_df['ingredients_fractional'].str.contains(r'gotas de')]

,name,ingredients,ingredients_fractional,entity,food
17,Panetone com gotas de chocolate,1 xícara (chá) de gotas de chocolate ou chocol...,1 xícara (chá) de gotas de chocolate ou chocol...,"{'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, ...",gotas de chocolate chocolate
247,Cookie com sorvete e café,3 cookies com gotas de chocolate,3 cookies com gotas de chocolate,"{'entities': [(0, 1, 'UNIDADE'), (2, 32, 'ALIM...",cookies com gotas de chocolate

In [113]:
# CORREÇÕES PONTUAIS/DIRETAS
ingredients_df.loc[ingredients_df['ingredients_fractional'] == '1 panetone caseiro de 500 g', 'entity'] = ingredients_df[ingredients_df['ingredients_fractional'] == '1 panetone caseiro de 500 g'].entity.map(lambda x: {'entities': x['entities'][:-1]})

ingredients_df.loc[ingredients_df['ingredients_fractional'] == '2 tiras finas da casca de limão', ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (17, 31, 'ALIMENTO')]}, 'casca de limão'

ingredients_df.loc[ingredients_df['ingredients'] == '¼ de xícara (chá) de banana-passa cortada em rodelas 1 cm', 'entity']  = ingredients_df[ingredients_df['ingredients'] == '¼ de xícara (chá) de banana-passa cortada em rodelas 1 cm'].entity.map(lambda x: {'entities': x['entities'][:-1]})

ingredients_df.loc[(ingredients_df['name'] == 'Ovinhos pintados') & (ingredients_df['food'] == 'ovos brancos'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE')]}, ''

ingredients_df.loc[(ingredients_df['name'] == 'Ovinhos de chocolate') & (ingredients_df['food'] == 'ovos brancos'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE')]}, ''

ingredients_df.loc[ingredients_df['ingredients'] == '6 folhas bem bonitas de rosa', ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (2, 8, 'ALIMENTO'), (21, 28, 'ALIMENTO')]}, 'folhas de rosa'

ingredients_df.loc[ingredients_df['ingredients'] == '4 colheres (sopa) do recheio de sua preferência (geléia de frutas, doce de leite, goiabada cremosa)', ['entity', 'food']] = {'entities': [(0, 17, 'MEDIDA_CASEIRA'), (49, 65, 'ALIMENTO'), (67, 80, 'ALIMENTO'), (82, 98, 'ALIMENTO')]}, 'geléia de frutas, doce de leite, goiabada cremosa'

ingredients_df.loc[ingredients_df['ingredients'] == '¾ de xícara (chá) de blueberry (ou mirtilo)', ['entity', 'food']] = {'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, 32, 'ALIMENTO'), (37, 44, 'ALIMENTO')]}, 'blueberry, mirtilo'

ingredients_df.loc[ingredients_df['ingredients'] == 'corantes para chocolate (hipossolúveis) , nas cores: vermelho, azul e amarelo', ['entity', 'food']] = {'entities': [(0, 23, 'ALIMENTO')]}, 'corantes para chocolate'

ingredients_df.drop(ingredients_df.query("name == 'Casca de ovos para decorar e rechear'").index, inplace=True)

###############################
ingredients_df.loc[ingredients_df['ingredients'] == '1 xícara (chá) de castanha-de-caju torrada, sem sal (cerca de 200g)', ['entity', 'food']] = {'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, 51, 'ALIMENTO'), (62, 66, 'MEDIDA_PADRAO')]}, 'castanha-de-caju torrada, sem sal'

ingredients_df.loc[ingredients_df['ingredients'] == '⅓ de xícara (chá) de castanha-de-caju torrada, sem sal', ['entity', 'food']] = {'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, 56, 'ALIMENTO')]}, 'castanha-de-caju torrada, sem sal'

ingredients_df.loc[ingredients_df['ingredients'] == '2½ colheres (sopa) de óleo (ou manteiga derretida)', ['entity', 'food']] = {'entities': [(0, 20, 'MEDIDA_CASEIRA'), (24, 28, 'ALIMENTO'), (33, 41, 'ALIMENTO')]}, 'óleo manteiga'

ingredients_df.loc[ingredients_df['ingredients'] == 'óleo (ou manteiga) para untar a frigideira', ['entity', 'food']] = {'entities': [(0, 4, 'ALIMENTO'), (9, 17, 'ALIMENTO')]}, 'óleo manteiga'

ingredients_df.loc[ingredients_df['ingredients'] == '1½ xícara (chá) de frutas variadas picadas (melão, morango, kiwi...)', ['entity', 'food']] = {'entities': [(0, 17, 'MEDIDA_CASEIRA'), (21, 27, 'ALIMENTO'), (46, 51, 'ALIMENTO'), (53, 60, 'ALIMENTO'), (62, 66, 'ALIMENTO')]}, 'frutas melão morango kiwi'

ingredients_df.loc[ingredients_df['ingredients'] == '1 colher (chá) de raspas de laranja ou de limão', ['entity', 'food']] = {'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, 35, 'ALIMENTO'), (42, 47, 'ALIMENTO')]}, 'raspas de laranja limão'

ingredients_df.loc[ingredients_df['ingredients'] == '½ xícara (chá) de vinho tinto (ou 1 xícara (chá) de vinho Marsala)', ['entity', 'food']] = {'entities': [(0, 16, 'MEDIDA_CASEIRA'), (20, 31, 'ALIMENTO'), (36, 50, 'MEDIDA_CASEIRA'), (54, 67, 'ALIMENTO')]}, 'vinho tinto vinho Marsala'

ingredients_df.loc[ingredients_df['ingredients'] == '2½ xícaras (chá) de fruta vermelha (morango, framboesa e amora - cerca de 350 g)', ['entity', 'food']] = {'entities': [(0, 18, 'MEDIDA_CASEIRA'), (22, 36, 'ALIMENTO'), (38, 45, 'ALIMENTO'), (47, 56, 'ALIMENTO'), (59, 64, 'ALIMENTO'), (76, 81, 'MEDIDA_PADRAO')]}, 'fruta vermelha morango framboesa amora'

ingredients_df.loc[ingredients_df['ingredients'] == 'óleo (ou manteiga) para untar a assadeira', ['entity', 'food']] = {'entities': [(0, 4, 'ALIMENTO'), (9, 17, 'ALIMENTO')]}, 'óleo manteiga'

ingredients_df.loc[ingredients_df['ingredients'] == '¼ de xícara (chá) de café coado, água ou o licor de sua preferência', ['entity', 'food']] = {'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, 27, 'ALIMENTO'), (35, 39, 'ALIMENTO'), (45, 50, 'ALIMENTO')]}, 'café água licor'

ingredients_df.loc[ingredients_df['ingredients'] == '1 xícara (chá) de gotas de chocolate ou chocolate cortado em cubinhos (cerca de 150 g)', ['entity', 'food']] = {'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, 36, 'ALIMENTO'), (40, 49, 'ALIMENTO'), (80, 85, 'MEDIDA_PADRAO')]}, 'gotas de chocolate chocolate'

ingredients_df.loc[ingredients_df['ingredients'] == '2½ xícaras (chá) de frutas vermelhas congeladas (cerca de 350g de morango, framboesa e amora)', ['entity', 'food']] = {'entities': [(0, 18, 'MEDIDA_CASEIRA'), (22, 38, 'ALIMENTO'), (60, 64, 'MEDIDA_PADRAO'), (68, 75, 'ALIMENTO'), (77, 86, 'ALIMENTO'), (89, 94, 'ALIMENTO')]}, 'frutas vermelhas morango framboesa amora'

ingredients_df.loc[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambola\b'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (2, 11, 'ALIMENTO')]}, 'carambola'

ingredients_df.loc[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambolas'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (2, 12, 'ALIMENTO')]}, 'carambolas'

/tmp/ipykernel_1233325/2373070628.py:47: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ingredients_df.loc[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambola\b'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (2, 11, 'ALIMENTO')]}, 'carambola'
/tmp/ipykernel_1233325/2373070628.py:49: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ingredients_df.loc[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambolas'), ['entity', 'food']] = {'entities': [(0, 1, 'UNIDADE'), (2, 12, 'ALIMENTO')]}, 'carambolas'

In [114]:
ingredients_df[ingredients_df['ingredients'] == '¼ de xícara (chá) de banana-passa cortada em rodelas 1 cm']
# ingredients_df[ingredients_df['ingredients_fractional'] == '2 tiras finas da casca de limão']
# ingredients_df[ingredients_df['ingredients'] == '6 folhas bem bonitas de rosa']
# ingredients_df[ingredients_df['ingredients'] == '4 colheres (sopa) do recheio de sua preferência (geléia de frutas, doce de leite, goiabada cremosa)']
# ingredients_df[ingredients_df['ingredients'] == '¾ de xícara (chá) de blueberry (ou mirtilo)']
# ingredients_df[ingredients_df['ingredients'] == 'corantes para chocolate (hipossolúveis) , nas cores: vermelho, azul e amarelo']
# ingredients_df.query("food == 'pincel'")
# ingredients_df[ingredients_df['ingredients_fractional'] == '2 tiras finas da casca de limão']
# ingredients_df.query("name == 'Casca de ovos para decorar e rechear'")

# ingredients_df.query("food == 'pincel'")
# ingredients_df.loc[ingredients_df['name'] == 'Ovinhos de chocolate']
# ingredients_df.loc[ingredients_df['name'] == 'Ovinhos pintados']
# ingredients_df.loc[(ingredients_df['food'].str.contains(r'\bovo(s\s+\w+)?'))]

# papel-manteiga e grãos de feijão cru para assar (ou outro grão seco da despensa) (329)
# ingredients_df.loc[329]

# ingredients_df.loc[63]
# ingredients_df[ingredients_df['ingredients_fractional'] == '30 forminhas de papel para brigadeiro (número 5)']

# ingredients_df[ingredients_df['ingredients_fractional'] == '5 fôrmas descartáveis para minipanetone de 7 cm de diâmetro']
# ingredients_df[ingredients_df['ingredients_fractional'] == '3 canudos de papel']
# ingredients_df[ingredients_df['ingredients_fractional'] == 'papel-manteiga e grãos de feijão cru para assar (ou outro grão seco da despensa)']
# ingredients_df[ingredients_df['ingredients_fractional'].str.contains(fr'\b{quantity_regex}\s+\bbola')]
# ingredients_df[ingredients_df['ingredients'] == '⅓ de xícara (chá) de castanha-de-caju torrada, sem sal']
# ingredients_df[ingredients_df['ingredients'] == '1½ xícara (chá) de frutas variadas picadas (melão, morango, kiwi...)']
# ingredients_df[ingredients_df['ingredients'] == '1 colher (chá) de raspas de laranja ou de limão']
# ingredients_df[ingredients_df['ingredients'] == '½ xícara (chá) de vinho tinto (ou 1 xícara (chá) de vinho Marsala)']
# ingredients_df[ingredients_df['ingredients'] == '2½ xícaras (chá) de fruta vermelha (morango, framboesa e amora - cerca de 350 g)']
# ingredients_df[ingredients_df['ingredients'] == 'óleo (ou manteiga) para untar a assadeira']
# ingredients_df[ingredients_df['ingredients'] == '¼ de xícara (chá) de café coado, água ou o licor de sua preferência']
# ingredients_df[ingredients_df['ingredients'] == '1 xícara (chá) de gotas de chocolate ou chocolate cortado em cubinhos (cerca de 150 g)']
# ingredients_df.loc[ingredients_df['ingredients'] == '2½ xícaras (chá) de frutas vermelhas congeladas (cerca de 350g de morango, framboesa e amora)', ['entity', 'food']] = {'entities': [(0, 18, 'MEDIDA_CASEIRA'), (22, 38, 'ALIMENTO'), (60, 64, 'MEDIDA_PADRAO'), (68, 75, 'ALIMENTO'), (77, 86, 'ALIMENTO'), (89, 94, 'ALIMENTO')]}, 'frutas vermelhas morango framboesa amora'
# ingredients_df[ingredients_df['ingredients'] == '2½ xícaras (chá) de frutas vermelhas congeladas (cerca de 350g de morango, framboesa e amora)']
# ingredients_df[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambola\b')] 

# ingredients_df[ingredients_df['ingredients'].str.contains(fr'\b{quantity_regex}\s+carambola')]

,name,ingredients,ingredients_fractional,entity,food
157,Granola na Air Fryer da Rita Lobo,¼ de xícara (chá) de banana-passa cortada em r...,1⁄4 de xícara (chá) de banana-passa cortada em...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, ...",banana-passa

In [115]:
ingredients_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3003 entries, 0 to 383
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    3003 non-null   object
 1   ingredients             3003 non-null   object
 2   ingredients_fractional  3003 non-null   object
 3   entity                  3003 non-null   object
 4   food                    3003 non-null   object
dtypes: object(5)
memory usage: 140.8+ KB

In [116]:
ingredients_df

,name,ingredients,ingredients_fractional,entity,food
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 colher (sopa) de manteiga gelada,1 colher (sopa) de manteiga gelada,"{'entities': [(0, 15, 'MEDIDA_CASEIRA'), (19, ...",manteiga
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de açúcar,2 colheres (sopa) de açúcar,"{'entities': [(0, 17, 'MEDIDA_CASEIRA'), (21, ...",açúcar
0,Muffin de mirtilo na Air Fryer da Rita Lobo,2 colheres (sopa) de farinha de trigo,2 colheres (sopa) de farinha de trigo,"{'entities': [(0, 17, 'MEDIDA_CASEIRA'), (21, ...",farinha de trigo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,¾ de xícara (chá) de mirtilo (cerca de 125 g),3⁄4 de xícara (chá) de mirtilo (cerca de 125 g),"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, ...",mirtilo
0,Muffin de mirtilo na Air Fryer da Rita Lobo,1 xícara (chá) de farinha de trigo,1 xícara (chá) de farinha de trigo,"{'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, ...",farinha de trigo
...,...,...,...,...,...
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de açúcar,1⁄2 xícara (chá) de açúcar,"{'entities': [(0, 16, 'MEDIDA_CASEIRA'), (20, ...",açúcar
383,Torta de castanha-de-caju e damasco,2 ovos,2 ovos,"{'entities': [(0, 1, 'UNIDADE'), (2, 6, 'ALIME...",ovos
383,Torta de castanha-de-caju e damasco,½ xícara (chá) de castanha-de-caju torrada sem...,1⁄2 xícara (chá) de castanha-de-caju torrada s...,"{'entities': [(0, 16, 'MEDIDA_CASEIRA'), (20, ...",castanha-de-caju torrada sem sal
383,Torta de castanha-de-caju e damasco,⅔ de xícara (chá) de damasco seco cortado em c...,2⁄3 de xícara (chá) de damasco seco cortado em...,"{'entities': [(0, 19, 'MEDIDA_CASEIRA'), (23, ...",damasco seco
383,Torta de castanha-de-caju e damasco,1 colher (chá) de amido de milho,1 colher (chá) de amido de milho,"{'entities': [(0, 14, 'MEDIDA_CASEIRA'), (18, ...",amido de milho

In [117]:
recipes_df_raw = pd.read_json('panelinha_dessert_recipes_cleaned.json')

In [ ]:
recipes_df_raw['total_ingredients'] = recipes_df_raw['ingredients'].apply(lambda listas: sum(len(lista) for lista in listas))
recipes_df_raw.head(10)

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients,total_ingredients
0,Muffin de mirtilo na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-9355-blog-muf...,Mirtilo e limão-siciliano são uma dupla e tant...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12
1,Muffin de maçã na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mac...,https://i.panelinha.com.br/i1/bk-3626-blog-muf...,O melhor deste muffin está no contraste: a mas...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12
2,Muffin de chocolate com laranja na Air Fryer d...,doces,https://panelinha.com.br/receita/muffin-de-cho...,https://i.panelinha.com.br/i1/bk-1389-blog-muf...,"Nesta receita, gotas de chocolate derretem na ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12
3,Muffin de banana na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-ban...,https://i.panelinha.com.br/i1/bk-3625-blog-muf...,"Banana e canela deixam a massa macia, úmida e ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12
4,Maçã assada na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/maca-assada-n...,https://i.panelinha.com.br/i1/bk-5932-blog-mac...,"Maçã, canela, mel e Air Fryer: com poucos ingr...","[[1 maçã (fuji ou gala), 2 colheres (chá) de m...",Panelinha,Pá-Pum,Até 2 porções,"[[Lave, seque e corte a maçã ao meio no sentid...",{},3
5,Bolo de iogurte com chá Earl Grey,doces,https://panelinha.com.br/receita/bolo-de-iogur...,https://i.panelinha.com.br/i1/bk-5319-blog-bol...,"Perfumado e fofinho, este bolo leva chá Earl G...",[[1 xícara (chá) de iogurte natural sem açúcar...,Panelinha,Até 1h,12 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{},9
6,Muffin de mirtilo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-7970-blog-muf...,O sucesso deste muffin está no contraste de te...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Até 1h,9 unidades,"[[Numa tigela, misture os ingredientes com a p...",{},11
7,Choux com chocolate e raspas de laranja,doces,https://panelinha.com.br/receita/choux-com-cho...,https://i.panelinha.com.br/i1/bk-2502-chouxcot...,"Com gotas de chocolate e raspas de laranja, a ...","[[50 g de manteiga em ponto pomada, ⅓ de xícar...",Panelinha,Até 2h,14 unidades,"[[Na tigela da batedeira, coloque todos os ing...",{},12
8,Cobertura de bolo (ganache),doces,https://panelinha.com.br/receita/cobertura-de-...,https://i.panelinha.com.br/i1/bk-4162-blog-cob...,A receita perfeita de ganache existe: textura ...,"[[1¾ de xícara (chá) de creme de leite fresco,...",Panelinha,Até 1h,essa receita cobre 12 bolinhos individuais (ou...,"[[Caso não esteja usando chocolate em gotas, p...",{},5
9,Bolinho de chocolate com ganache,doces,https://panelinha.com.br/receita/bolinho-de-ch...,https://i.panelinha.com.br/i1/bk-8769-blog-bol...,Chocolate e ganache formam uma dupla difícil d...,[[2¼ de xícaras (chá) de chocolate 55% cacau e...,Panelinha,Mais de 2h,12 minibolos,"[[Caso não esteja usando chocolate em gotas, p...",{},15

In [183]:
# ['1 colher (sopa) de manteiga gelada',
#  '2 colheres (sopa) de açúcar',
#  '2 colheres (sopa) de farinha de trigo',
#  '¾ de xícara (chá) de mirtilo (cerca de 125 g)',
#  '1 xícara (chá) de farinha de trigo',
#  '¾ de xícara (chá) de açúcar',
#  '1 colher (chá) de fermento em pó',
#  'raspas de 1 limão-siciliano',
#  '1 ovo',
#  '⅓ de xícara (chá) de iogurte natural sem açúcar nem adoçante',
#  '50 g de manteiga',
#  'manteiga e farinha de trigo para untar e polvilhar as forminhas']

# recipes_df_raw['ingredients'].head()
import re
parts = [['1 colher (sopa) de manteiga gelada', '2 colheres (sopa) de açúcar', '2 colheres (sopa) de farinha de trigo'], ['¾ de xícara (chá) de mirtilo (cerca de 125 g)', '1 xícara (chá) de farinha de trigo', '¾ de xícara (chá) de açúcar', '1 colher (chá) de fermento em pó', 'raspas de 1 limão-siciliano', '1 ovo', '⅓ de xícara (chá) de iogurte natural sem açúcar nem adoçante', '50 g de manteiga', 'manteiga e farinha de trigo para untar e polvilhar as forminhas']]
# [item for part in parts for item in part]
[re.match(r'.*\bcolher\b.*', ingredient, re.IGNORECASE) is not None for ingredient in [item for part in parts for item in part]]
# if re.match(r'.*\bcolher\b.*', '1 Colher (sopa) de manteiga gelada', re.IGNORECASE):
#     print('Match found')
# else: 
#     print('No match found')

[True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False]

In [ ]:
recipes_df_raw['total_steps'] = recipes_df_raw['steps'].map(lambda parts: sum(len(part) for part in parts))
recipes_df_raw.head(10)
# 'Misture os ingredientes com a ponta dos dedos até formar uma farofinha. Reserve.', 
# 'Unte com manteiga 9 forminhas individuais de muffin que possam ir ao forno. Polvilhe farinha de trigo, chacoalhe para espalhar e bata na pia para tirar o excesso. Se preferir use forminhas de papel específicas para muffin em vez de untar.', 
# 'Coloque a manteiga numa tigela pequena e leve ao micro-ondas para rodar por cerca de 1 minuto ou até derreter.', 
# 'Numa tigela grande, misture a farinha com o açúcar, o fermento e as raspas de limão. Abra um buraco no centro, adicione o ovo, o iogurte e a manteiga derretida e misture bem com o batedor de arame até a massa ficar lisa.', 
# 'Separe ¼ de xícara (chá) dos mirtilos para finalizar os muffins e adicione o restante à massa. Misture delicadamente com uma espátula.', 
# 'Preencha cada forminha com cerca de ¼ de xícara (chá) de massa, ou até preencher ⅔ da capacidade. Distribua os mirtilos reservados sobre os muffins e cubra com a farofinha.', 
# 'Preaqueça a Air Fryer da linha Electrolux por Rita Lobo a 160 °C e programe para assar por 30 minutos (os muffins vão assar em duas levas de cerca de 15 minutos cada).', 
# 'Coloque quantos muffins couberem na Air Fryer, um ao lado do outro e asse por cerca de 15 minutos, ou até dourarem. Repita com o restante e deixe esfriar completamente antes de servir.'

,name,category,link,img,description,ingredients,author,time,serves,steps,nutrients,total_ingredients,total_steps
0,Muffin de mirtilo na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-9355-blog-muf...,Mirtilo e limão-siciliano são uma dupla e tant...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12,8
1,Muffin de maçã na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-mac...,https://i.panelinha.com.br/i1/bk-3626-blog-muf...,O melhor deste muffin está no contraste: a mas...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12,7
2,Muffin de chocolate com laranja na Air Fryer d...,doces,https://panelinha.com.br/receita/muffin-de-cho...,https://i.panelinha.com.br/i1/bk-1389-blog-muf...,"Nesta receita, gotas de chocolate derretem na ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12,7
3,Muffin de banana na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/muffin-de-ban...,https://i.panelinha.com.br/i1/bk-3625-blog-muf...,"Banana e canela deixam a massa macia, úmida e ...","[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Pá-Pum,9 unidades,[[Misture os ingredientes com a ponta dos dedo...,{},12,7
4,Maçã assada na Air Fryer da Rita Lobo,doces,https://panelinha.com.br/receita/maca-assada-n...,https://i.panelinha.com.br/i1/bk-5932-blog-mac...,"Maçã, canela, mel e Air Fryer: com poucos ingr...","[[1 maçã (fuji ou gala), 2 colheres (chá) de m...",Panelinha,Pá-Pum,Até 2 porções,"[[Lave, seque e corte a maçã ao meio no sentid...",{},3,3
5,Bolo de iogurte com chá Earl Grey,doces,https://panelinha.com.br/receita/bolo-de-iogur...,https://i.panelinha.com.br/i1/bk-5319-blog-bol...,"Perfumado e fofinho, este bolo leva chá Earl G...",[[1 xícara (chá) de iogurte natural sem açúcar...,Panelinha,Até 1h,12 porções,[[Preaqueça o forno a 180 ºC (temperatura médi...,{},9,6
6,Muffin de mirtilo,doces,https://panelinha.com.br/receita/muffin-de-mir...,https://i.panelinha.com.br/i1/bk-7970-blog-muf...,O sucesso deste muffin está no contraste de te...,"[[1 colher (sopa) de manteiga gelada, 2 colher...",Panelinha,Até 1h,9 unidades,"[[Numa tigela, misture os ingredientes com a p...",{},11,6
7,Choux com chocolate e raspas de laranja,doces,https://panelinha.com.br/receita/choux-com-cho...,https://i.panelinha.com.br/i1/bk-2502-chouxcot...,"Com gotas de chocolate e raspas de laranja, a ...","[[50 g de manteiga em ponto pomada, ⅓ de xícar...",Panelinha,Até 2h,14 unidades,"[[Na tigela da batedeira, coloque todos os ing...",{},12,13
8,Cobertura de bolo (ganache),doces,https://panelinha.com.br/receita/cobertura-de-...,https://i.panelinha.com.br/i1/bk-4162-blog-cob...,A receita perfeita de ganache existe: textura ...,"[[1¾ de xícara (chá) de creme de leite fresco,...",Panelinha,Até 1h,essa receita cobre 12 bolinhos individuais (ou...,"[[Caso não esteja usando chocolate em gotas, p...",{},5,3
9,Bolinho de chocolate com ganache,doces,https://panelinha.com.br/receita/bolinho-de-ch...,https://i.panelinha.com.br/i1/bk-8769-blog-bol...,Chocolate e ganache formam uma dupla difícil d...,[[2¼ de xícaras (chá) de chocolate 55% cacau e...,Panelinha,Mais de 2h,12 minibolos,"[[Caso não esteja usando chocolate em gotas, p...",{},15,10